### ISSUE TITLE
Create boolean variables list in beginning of script to on/off stuff

### ISSUE THREAD

**Issue by asd-and-Rizzo** [Disassembler0/Win10-Initial-Setup-Script#1]
As of now i have to comment out stuff in mid of script. It would be more reusable to have named conditional variables in start of script to set true or false. Same variables could be set from command line.

**Comment by NeverMine17** [comment]
> Same variables could be set from command line.

Here is an example of that:
```ps1
$DisableCortana = $args[0]
```

**Comment by Disassembler0** [comment]
The initial idea is to have the script only as a set of building blocks for customization as I'm pretty sure that sysadmins who are potentially using it in larger scopes are heavily modifying it and incorporating it into their own much larger script suites.

Nevertheless, I have in mind for some months (maybe years) an idea to have "presets". The idea is that you'll have an external file with list of modifications which you then pass as an argument to the script and it would do only whatever is defined in the preset. That way, you can have still the same vanilla script, but one set of modifications for you and your family and another for work/clients/whatever. In case you don't pass any preset, default values (which can be defined in start of the script, as suggested by OP) will be applied. So far I was only lacking the time and motivation to do that.

**Comment by Disassembler0** [comment]
OK, new functionality implemented. Hope it satisfies your needs like this.
