### ISSUE TITLE
Unpinning of Edge and Store from Taskbar

### ISSUE THREAD

**Issue by Sirove** [Disassembler0/Win10-Initial-Setup-Script#107]
Thanks for this clean and absolutely essential Script! Would be nice if you could also add functions for unpinning Microsoft Edge and the Windows Store from the Taskbar. There is a [StackOverflow question](https://stackoverflow.com/questions/45152335/unpin-the-microsoft-edge-and-store-taskbar-shortcuts-programmatically) showing how to achieve this.

**Comment by Disassembler0** [comment]
`UnpinTaskbarIcons` already does that. You just have to uncomment it or create your own preset and use it there.
