### ISSUE TITLE
splitting the script into 2, one admin and one user script

### ISSUE THREAD

**Issue by thomasboehm** [Disassembler0/Win10-Initial-Setup-Script#11]
Hi, 

wouldn't it be better to split the whole script into 2 scripts, one that needs admin privileges (changes to HKLM) and one that runs with standard user privileges (changes to HKCU)? This way you wouldn't need to give users temporarily admin privileges and could run the script(s) in your logon script.

Just an idea...

**Comment by Disassembler0** [comment]
As the FAQ states, the script is mostly aimed to be used directly after clean installation in single-user environments. The ultimate goal would be to move everything to GPO and not have any HKCU modifications at all, but that's hardly possible.

I was thinking to move the auto-elevation code into a separate function, so the user can decide if they'd like to elevate just by calling the function. That would satisfy your needs but it would also be a breaking change for already existing presets. The benefit of carrying out such change is marginal as only several GUI tweaks can be applied without elevation.

Anyway, check the [elevate-on-demand branch](https://github.com/Disassembler0/Win10-Initial-Setup-Script/tree/app-pinning), which implements that change. I'll leave it separate for the moment and think about all the implications which this might have before merging it into master.

**Comment by Disassembler0** [comment]
Merged to master in 727bf0d09b4985c2a436a3b1e92ddf9aba410931 for v2.8 release.
