### ISSUE TITLE
most used app in start menu

### ISSUE THREAD

**Issue by peekaa** [Disassembler0/Win10-Initial-Setup-Script#110]
Would it be possible to control whether to show or not most used app in the top of start menu? Thank you.

**Comment by r3incarnat0r** [comment]
It's included in the DisableAppSuggestions tweak.

**Comment by peekaa** [comment]
Its this "Start_TrackProgs"?

**Comment by Disassembler0** [comment]
Yes, that's the one. Would it make more sense to have it as a separate tweak?

**Comment by peekaa** [comment]
As for me yes, cause that is what i miss, as for win7 start menu. That is more usefull than unusefull. Thank you.

**Comment by Disassembler0** [comment]
Okay. I've just found out that the `Start_TrackProgs` is no longer valid on 1803. And neither is the *[Remove frequent programs list from the Start Menu](https://docs.microsoft.com/en-us/windows/configuration/changes-to-start-policies-in-windows-10)* policy setting `NoStartMenuMFUprogramsList` registry value. Instead, the flag is now buried somewhere deep down in `HKCU\Software\Microsoft\Windows\CurrentVersion\CloudStore\Store\Cache\DefaultAccount\ *windows.data.unifiedtile.startglobalproperties\Current\Data`

So I'll remove the line completely for the time being.

**Comment by r3incarnat0r** [comment]
I have 1803 and Start_TrackProgs is still changing in registry when switching "Let Windows track app launches to improve Start and search results" and vice versa. Yes, there are four bytes "randomly" jumping in CloudStore, too, but isn't Start_TrackProgs still the primary switch? Please gimme some hint or link if I'm wrong, thanks.

**Comment by r3incarnat0r** [comment]
Thanks for info. Seems like Start_TrackProgs shouldn't be touched alone anymore, as it screws ui switches thinking track app launches is disabled while it's enabled and just greys control of showing used apps. Well done MS, now someone must do research and dig out a proper api calls I guess or we can just forget these tweaks. :/

**Comment by r3incarnat0r** [comment]
OK, good to know, saved me from wasting some time. :) Anyway, speaking about history tracking things, I looked on other Start Menu setting switches and maybe found two of them worth adding to script - _Show recently added apps_ and _Show recently opened items in Jump Lists on Start or the taskbar_. I commited it to my last PR.
