### ISSUE TITLE
Consider adapting some features from O&O ShutUp10

### ISSUE THREAD

**Issue by Zero3** [Disassembler0/Win10-Initial-Setup-Script#112]
I noticed the existence of another tool, [O&O ShutUp10](https://www.oo-software.com/en/shutup10), which contains a lot of privacy focused tweaks similar to some of the ones in Win10-Initial-Setup-Script.

After executing Win10-Initial-Setup-Script with most of the privacy oriented tweaks enabled, only about half of the things that ShutUp10 supports are disabled. Some of the remaining ones are probably not relevant for the scope of Win10-Initial-Setup-Script, but I think some of them could very well be.

This is merely meant as a suggestion to have a look at ShutUp10 for inspiration, and consider adapting any relevant features missing in Win10-Initial-Setup-Script. I'm not requesting any one of them in particular :).

**Comment by Disassembler0** [comment]
So, I've checked out the tool. Basically...

 - The tool checks for specific values on specific places. So just the fact that some setting remain red doesn't mean anything as a tweak with the same effect can be applied in another place. Most notably in cases where the O&O tool sets the values directly but my script sets them via GPO instead.
 - Some settings (resp. keys which the app uses) are outdated even in the latest release from this month.
 - There are also a few tweaks which I had in my script in the past but got rid of them as they were based on FUD and unconfirmed rumors (DiagTrack, WAP push).
 - Some settings are dependent on each other and IMO it doesn't have much sense to have them separately. E.g. Application compatibility inventory collector depends on Customer Experience Improvement Program. If CEIP is disabled, inventory collector is disabled too.
 - Furthermore I see there a bunch of settings which strip functionality which I deem useful (biometrics, access to peripherals, password reveal, steps recorder etc.)

That being said, there *are* some setting which look quite interesting and are worth researching further and I'll follow up on them. Nevertheless, if you think that the tweaks in my script are lacking some functionality or they are downright faulty, I'd rather see an issue (or PR) for the specific problems. Issue like this one isn't very constructive as there is no baseline or standard which the tools need to meet, so there is no point in comparing them.

**Comment by Disassembler0** [comment]
Okay, so it seems that even those which I wanted to follow up on (app telemetry and inking+typing recognition), are dependent on CEIP. So there is no need to add more keys for the tweaks. There would be need to add more keys to shut up the O&O ShutUp, however that's not the goal of the script :)

**Comment by Zero3** [comment]
@Disassembler0 You are awesome! Thanks! :tada:
