### ISSUE TITLE
Enable or Disable "Always show all icons in the notification area

### ISSUE THREAD

**Issue by driscollw** [Disassembler0/Win10-Initial-Setup-Script#114]
https://www.tenforums.com/tutorials/5313-hide-show-notification-area-icons-taskbar-windows-10-a.html 

Enable or Disable "Always show all icons in the notification area" for All Users using a REG file

 You must be signed in as an administrator to do this option.

 The downloadable .reg files below will add and modify the DWORD value in the registry keys below.

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer

NoAutoTrayNotify DWORD

(delete) = Disable
1 = Enable

**Comment by Disassembler0** [comment]
`ShowTrayIcons` tweak already does that. But I guess you're interested in the "*all users*" part, right?

**Comment by driscollw** [comment]
I guess I should provide more info, sorry about that. I currently have the ShowTrayIcons flag on, but doesn't seem to work. I run an elevated powershell and think maybe that could be causing it. Not sure of the difference between EnableAutoTray vs NoAutoTrayNotify. This is on RS4.

**Comment by driscollw** [comment]
I just did a fresh install on another laptop I have and the ShowTrayIcons worked.....who knows. The one it didn't work on was a older Thinkpad T420, not sure how that would make a difference. Just strange.

**Comment by Disassembler0** [comment]
One way or another, setting things via GPO is much more reliable, so I'll look into your proposal anyway. Don't close the issue just yet, please.
