### ISSUE TITLE
idea: review NSA "windows secure baseline" settings.

### ISSUE THREAD

**Issue by alirobe** [Disassembler0/Win10-Initial-Setup-Script#117]
Stumbled across this, and thought you might appreciate it 🙂

Just a note to suggest you might like to review & see if you find anything useful from it. 

https://github.com/nsacyber/Windows-Secure-Host-Baseline

**Comment by Disassembler0** [comment]
I was checking it about a half a year ago. There are a lot of things unrelated to the OS itself (Office, Adobe Reader, Chrome, ...), things which require explicit whitelisting (AppLocker, Device Guard, ...) and things which require hardware assistance to work properly (SecureBoot, TPM, BitLocker, SmartCard, ...).

Back then I couldn't find anything what would be really beneficial. However you're more than welcome to review it yourself and tell me which specific parts would you like to see in my script.

**Comment by alirobe** [comment]
I had a look and found pretty much the same thing. Thought it was worth bringing to your attention really just in case you missed it. Thanks :)
