### ISSUE TITLE
Run-time error, need help

### ISSUE THREAD

**Issue by kameleon132** [Disassembler0/Win10-Initial-Setup-Script#124]
Hello everyone,
I have used , everything works great, except one thing,
I have a issue when launching a specific .exe file.
When program is launched an error occurs, full message:

**Run-Time error '-2147417848 (80010108)':
Automation error
The object invoked has disconnected from its clients.**

Additional info:
Program uses USB TOKEN before launch, without inserted usb token program properly shouts for that token, after insterting token error occurs.
I tried to restore windows but it fails every time.
That program uses .mdb file so i think that there is a problem with visual basic or something similiar.
I was searching google but every issue similiar to me was with excel, word or something else and the solution didnt worked for me.

I gently ask for your help, i really need it, that program is important at my work.
Have a nice day

**Comment by Disassembler0** [comment]
By default the `Win10.ps1` disables execution of *.vbs scripts. The tweak which does it is called `DisableScriptHost`, so try running `EnableScriptHost` to restore the original behavior. Alternatively, you can also run this in elevated powershell (as admin)
```
Remove-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows Script Host\Settings" -Name "Enabled"
```
Restart will probably be needed afterwards.

Other that that, there isn't anything else related to VBA and there it's anything *at all* related to MS Office as that's entirely different product.
