### ISSUE TITLE
unpinstartmenu back

### ISSUE THREAD

**Issue by peekaa** [Disassembler0/Win10-Initial-Setup-Script#127]
I had done UnpinStartMenuTiles. Now, when I want to add some app to Startmenu, I can add one, and when try to add another one, all the StarMenu (right to to list of programs) disappears. Also - when I add one app and want like rename StartMenu (above), then the StartMenu disappears. 

Pls help.

**Comment by Disassembler0** [comment]
Can't reproduce.

The tweak is designed to sweep through tile collection caches and edits the existing caches so they contain empty collection. If the caches would be missing or corrupted, Windows would replace them with the default ones. Just tried that in VM on both English 1803 Home and Czech 1803 Pro without issues.

If the icons are misbehaving even after subsequent reboots, then try the following:

1. Open regedit
2. Navigate to `HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\CloudStore\Store\Cache\DefaultAccount`
3. Delete all the subkeys ending with `start.tilegrid$windows.data.curatedtilecollection.tilecollection`. If you applied the `UnpinStartMenuTiles` tweak, you should have just one. Be careful not to delete any other keys as there are more ending with `windows.data.curatedtilecollection.tilecollection`.
4. Reboot.
5. Windows will see that no caches are defined and try to restore the default ones similar to those you've seen after first installation (the apps and suggestions you've already uninstalled won't show)

**Comment by peekaa** [comment]
Thank you, Ill try.
