### ISSUE TITLE
Disable restore points, recovery and factory reset

### ISSUE THREAD

**Issue by dendenis82** [Disassembler0/Win10-Initial-Setup-Script#131]
#Off restore points 
#Off Windows Update service
#Off Recovery Windows

P.S. sorry if it`s not right place for suggestions, I`m not familiar with github.

**Comment by Disassembler0** [comment]
Hi,
The place is correct.

> #Off restore points

Yup. That can be added. There's even a PowerShell cmdlet for that (`Enable-ComputerRestore` / `Disable-ComputerRestore`). The only problem is that there doesn't seem to be a default which would be the same for all environments (e.g. Deskops have it on by default, VMs have it off, Server don't have that option at all), but that can be documented and overlooked.

> #Off Windows Update service

Turning off updates completely is a bad idea and I'm not gonna implement that one. There's already a bunch of tweaks which make the update process a bit more bearable.

> #Off Recovery Windows

If you're talking about the whole recovery environment partition, that can't be done as it's essential part of the system. If you're talking only about the option in *Settings* > *Update & Security* > *Recovery*, then it can be disabled via `reagentc.exe /disable`. The option and buttons will still remain there but if you attempt to recover, you'll get "*Could not find the recovery environment.*" error message. So this one could be added. Is this what you have in mind?

**Comment by dendenis82** [comment]
Hi, 
about recovery, 
after installing Windows I use commands in cmd;

bcdedit /set {current} bootstatuspolicy ignoreallfailures
bcdedit /set {current} recoveryenabled no

Does "reagentc.ext  /disable" the same?

**Comment by Disassembler0** [comment]
I've checked just now and `reagentc.exe /disable` does even a bit more. Among other things, it sets `recoveryenabled no` and removes `recoverysequence` GUID in *bcdedit*, so if you get to the F8 boot menu, the "*Repair your computer*" option is completely missing from there. And you can't even reset the PC to factory defaults from *Settings* > *Update & Security* > *Recovery* like I've already mentioned.

If you set only the *bcdedit* options you've listed, it's still possible to get to the recovery menu manually via F8 boot menu and it's possible also to initiate the factory reset.

So I'm thinking to have 2 tweaks for this.

1. Make boot always ignore errors, which would set just `bootstatuspolicy`.
2. Disable Recovery and factory reset, which would run `reagentc.exe /disable` which implicitly does also the `recoveryenabled` and `recoverysequence` magic.

Plus of course the third one for restore points. Any objections?

**Comment by dendenis82** [comment]
No objections.
_(maybe only these two tweaks could fit in one #command as they are chained, just to be more clear during first enabling/disabling options.)_
