### ISSUE TITLE
Press key and Reboot

### ISSUE THREAD

**Issue by truefriend-cz** [Disassembler0/Win10-Initial-Setup-Script#14]
Script have problem where not running complette script.
If comment lines...
```
### Auxiliary Functions ###
	#"WaitForKey",
	#"Restart"
```
If remove section then same problem.

Cz:
Zkoušel jsem odstranit také čárku za "EnableIEEnhancedSecurity",  aby se regulérně ukončila funkce ale také to nepomohlo.

**Comment by Disassembler0** [comment]
Smaž ukončovací čárku na posledním **ne**zakomentovaném řádku. EnableIEEnhancedSecurity máš evidentně zakomentované, takže tam to nemá vliv.

A upravit si kód a pak fňukat, že nefunguje, je celkem troufalé.

**Comment by truefriend-cz** [comment]
Ale já jsem vám tam psal, že jsem to už zkusil. Je to ta část, kde  píši Cz: a pak píši v češtině.... jste slepej?!?!?!?!?!?!?!?
Nejdříve si otestujte svůj vlastní script, než začnete někoho buzerovat. J za to, že si vůbec dovoluje stěžovat ještě navíc na místě tomu určeném!!!!!! Jste hovado, protože buzerovat toho, pro koho je defakto script určen, může opravdu jen hovado. (teď neposuzuji to co jste naprogramoval) A pro ostatní, kdo by čekal na řešení tak jsem dřív na něj přišel já, zatímco vy tu buzerujete jak ten kokot.
Řešení je na konec funkce scriptu umístit dvě uvozovky... výběr z kódu:

Původní podoba:
`...
	# "DisablePasswordPolicy",      # "EnablePasswordPolicy",
	# "DisableCtrlAltDelLogin",     # "EnableCtrlAltDelLogin",
	# "DisableIEEnhancedSecurity",  # "EnableIEEnhancedSecurity",

	### Auxiliary Functions ###
	"WaitForKey",
	"Restart"
)



##########
# Privacy Settings
##########
..`

Upravená podoba:
`...
	"DisableCtrlAltDelLogin",     # "EnableCtrlAltDelLogin",
	"DisableIEEnhancedSecurity",  # "EnableIEEnhancedSecurity",

	### Auxiliary Functions ###
	#"WaitForKey",
	#"Restart"
	""
)



##########
# Privacy Settings
##########
...`

Problém je způsobený tím, že na konci každé funkce je očekáván příkaz a nesmí skončit otevřená. Pokud chcete ukončit funkci regulérně, tak místo dvou uvozovek napište příkaz Exit... Přiznávám, že jsem to netestoval, vyřešil jsem to těmi uvozovkami, ale mělo by to také fungovat.

**Comment by Disassembler0** [comment]
Píšu, že máš smazat čárku na posledním **nezakomentováném** řádku, resp. před posledním blokem komentářů, tedy v původní verzi skriptu hned za `"EnableF8BootMenu"`. Ty v prvním postu píšeš, žes ji místo toho smazal za `"EnableIEEnhancedSecurity"`, tedy **v komentáři**, kde to nemá žádný vliv.
Pokud jsi, skript modifikoval ještě jinak, třeba tak, že jsi odkomentoval `"DisableIEEnhancedSecurity"`, tak poslední čárka je hned za tím, protože `"EnableIEEnhancedSecurity"` máš v komentáři stále. Mimoto ti tu chybu zhruba takhle nějak reportoval PowerShell a vyznačil přesné místo, kde k ní došlo:

    At C:\Users\User\Desktop\Win10.ps1:92 char:21
    +     "EnableF8BootMenu",             # "DisableF8BootMenu",
    +                        ~
    Missing expression after ','.
        + CategoryInfo          : ParserError: (:) [], ParseException
        + FullyQualifiedErrorId : MissingExpressionAfterToken

Tvoje řešení bude díky přeskakování prázdných řetězců fungovat taky.

To, že jakékoliv úpravy a použití skriptu je na vlastní nebezpečí je ve FAQ i v licenci. Pokud kód svými úpravami rozbiješ a ani neřekneš, co jsi vlastně upravil, tak to opravím jen těžko, protože křišťálovou kouli nevlastním. Invektivy si laskavě odpusť.
