### ISSUE TITLE
In 1809 Build Activity History still ticked in settings

### ISSUE THREAD

**Issue by reinistihovs** [Disassembler0/Win10-Initial-Setup-Script#149]
Hi,
These keys should disable Activity history, but the setting still persists active in the settings menu.
Rebooted, tried on different machine, only fresh install.
 
	Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "EnableActivityFeed" -Type DWord -Value 0
	Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "PublishUserActivities" -Type DWord -Value 0
	Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "UploadUserActivities" -Type DWord -Value 0

So i went further to investigate, i tried to find what gets changed in registry, when i untick/tick activity history.... I made a registry snapshot, and compared it.

It looks like, the setting actually gets disabled, but still is shown active in settings menu.

This is what gets changed.

```
==================================================
Registry Key      : HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Notifications\Data
Change Type       : Modified Value
Value Name        : 418A073AA3BC3475
Value Data        : 12 02 00 00 00 00 00 00 04 00 04 00 01 02 0B 00 00 00 00 00 1A 00 00 00 0D 78 79 00 01 00 00 00 4A AA 81 00 09 00 00 00 6B 50 7E 00 03 00 00 00 87 DE 83 00 05 00 00 00 99 CB DC 00 01 00 00 00 9C A6 C3 00 80 04 00 00 A1 9F 5E 00 09 00 00 00 DB B4 EF 00 01 00 00 00 F1 D9 A3 00 01 00 00 00 F4 A4 C3 00 04 00 00 00 FE D3 7A 00 09 00 01 00 00 00 04 00 00 00 00 7D 75 00 02 00 00 00 08 68 E3 00 07 00 00 00 18 7D C7 00 4C 04 00 00 56 73 7D 00 44 00 00 00 6B 50 7E 00 01 00 00 00 8A 83 85 00 0A 00 00 00 98 29 B7 00 02 00 00 00 B0 87 B4 00 44 00 00 00 E6 C5 31 00 01 00 04 00 00 00 1C 00 00 00 1A 9C B2 00 02 00 05 00 00 00 10 00 00 00 9F C8 CA 00 01 00 00 00 A9 B2 DB 00 01 00 09 00 00 00 69 04 00 00 8A 83 85 00 09 00 65 00 00 00 CD 00 00 00 1C 95 5C 00 02 00 00 00 1E 76 B7 00 42 00 00 00 65 A6 9E 00 1D 00 00 00 77 9B 93 00 0B 00 00 00 85 50 AE 00 53 00 00 00 9C A6 B4 00 3D 01 00 00 A2 05 06 00 10 78 00 00 E6 C5 31 00 A6 07 00 00 F0 E0 B6 00 03 00 66 00 00 00 8D 00 00 00 65 A6 9E 00 1D 00 00 00 77 9B 93 00 D9 00 00 00 A2 05 06 00 02 00 67 00 00 00 01 00 00 00 9C A6 B4 00 60 00 00 00 A2 05 06 00 02 00 68 00 00 00 01 00 00 00 9C A6 B4 00 5F 02 00 00 A2 05 06 00 01 00 69 00 00 00 24 13 00 00 65 A6 9E 00 01 00 6B 00 00 00 06 00 00 00 65 A6 9E 00 01 00 70 00 00 00 16 00 00 00 65 A6 9E 00 01 00 71 00 00 00 02 00 00 00 65 A6 9E 00 01 00 72 00 00 00 28 01 00 00 A2 05 06 00 01 00 73 00 00 00 9E 00 00 00 65 A6 9E 00 01 00 75 00 00 00 02 00 00 00 65 A6 9E 00 01 00 76 00 00 00 35 00 00 00 65 A6 9E 00 01 00 77 00 00 00 06 00 00 00 65 A6 9E 00 01 00 78 00 00 00 0C 00 00 00 65 A6 9E 00 01 00 7B 00 00 00 02 00 00 00 65 A6 9E 00 01 00 7D 00 00 00 9A 00 00 00 65 A6 9E 00 01 00 7F 00 00 00 A4 00 00 00 65 A6 9E 00 01 00 81 00 00 00 19 00 00 00 65 A6 9E 00 01 00 97 00 00 00 0A 00 00 00 BE B3 EF 00 01 00 C0 01 00 00 05 00 00 00 1F C8 75 00 
Value Type        : REG_BINARY
Value Data Changed To: 13 02 00 00 00 00 00 00 04 00 04 00 01 02 0B 00 00 00 00 00 1A 00 00 00 0D 78 79 00 01 00 00 00 4A AA 81 00 09 00 00 00 6B 50 7E 00 03 00 00 00 87 DE 83 00 05 00 00 00 99 CB DC 00 01 00 00 00 9C A6 C3 00 80 04 00 00 A1 9F 5E 00 09 00 00 00 DB B4 EF 00 01 00 00 00 F1 D9 A3 00 01 00 00 00 F4 A4 C3 00 04 00 00 00 FE D3 7A 00 09 00 01 00 00 00 04 00 00 00 00 7D 75 00 02 00 00 00 08 68 E3 00 07 00 00 00 18 7D C7 00 4C 04 00 00 56 73 7D 00 44 00 00 00 6B 50 7E 00 01 00 00 00 8A 83 85 00 0A 00 00 00 98 29 B7 00 02 00 00 00 B0 87 B4 00 44 00 00 00 E6 C5 31 00 01 00 04 00 00 00 1C 00 00 00 1A 9C B2 00 02 00 05 00 00 00 10 00 00 00 9F C8 CA 00 01 00 00 00 A9 B2 DB 00 01 00 09 00 00 00 69 04 00 00 8A 83 85 00 09 00 65 00 00 00 D1 00 00 00 1C 95 5C 00 02 00 00 00 1E 76 B7 00 44 00 00 00 65 A6 9E 00 1D 00 00 00 77 9B 93 00 0B 00 00 00 85 50 AE 00 53 00 00 00 9C A6 B4 00 42 01 00 00 A2 05 06 00 10 78 00 00 E6 C5 31 00 B6 07 00 00 F0 E0 B6 00 03 00 66 00 00 00 92 00 00 00 65 A6 9E 00 1D 00 00 00 77 9B 93 00 DD 00 00 00 A2 05 06 00 02 00 67 00 00 00 01 00 00 00 9C A6 B4 00 61 00 00 00 A2 05 06 00 02 00 68 00 00 00 01 00 00 00 9C A6 B4 00 60 02 00 00 A2 05 06 00 01 00 69 00 00 00 84 13 00 00 65 A6 9E 00 01 00 6B 00 00 00 07 00 00 00 65 A6 9E 00 01 00 70 00 00 00 16 00 00 00 65 A6 9E 00 01 00 71 00 00 00 02 00 00 00 65 A6 9E 00 01 00 72 00 00 00 30 01 00 00 A2 05 06 00 01 00 73 00 00 00 A0 00 00 00 65 A6 9E 00 01 00 75 00 00 00 02 00 00 00 65 A6 9E 00 01 00 76 00 00 00 35 00 00 00 65 A6 9E 00 01 00 77 00 00 00 07 00 00 00 65 A6 9E 00 01 00 78 00 00 00 0C 00 00 00 65 A6 9E 00 01 00 7B 00 00 00 02 00 00 00 65 A6 9E 00 01 00 7D 00 00 00 9C 00 00 00 65 A6 9E 00 01 00 7F 00 00 00 A7 00 00 00 65 A6 9E 00 01 00 81 00 00 00 19 00 00 00 65 A6 9E 00 01 00 97 00 00 00 0B 00 00 00 BE B3 EF 00 01 00 C0 01 00 00 05 00 00 00 1F C8 75 00 
Value Type Changed To: REG_BINARY
Key Modified Time 1: 10/9/2018 1:40:11 PM
Key Modified Time 2: 10/9/2018 1:47:57 PM
==================================================

==================================================
Registry Key      : HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\VFUProvider
Change Type       : Modified Value
Value Name        : StartTime
Value Data        : 131835556200006452
Value Type        : REG_QWORD
Value Data Changed To: 131835556800059893
Value Type Changed To: REG_QWORD
Key Modified Time 1: 10/9/2018 1:47:00 PM
Key Modified Time 2: 10/9/2018 1:48:00 PM
==================================================

==================================================
Registry Key      : HKEY_LOCAL_MACHINE\System\ControlSet001\Services\bam\State\UserSettings\S-1-5-21-3713522059-1769593829-3801301658-1001
Change Type       : Modified Value
Value Name        : windows.immersivecontrolpanel_cw5n1h2txyewy
Value Data        : 1A B5 17 D6 AF 5F D4 01 00 00 00 00 00 00 00 00 01 00 00 00 02 00 00 00 
Value Type        : REG_BINARY
Value Data Changed To: D7 54 F1 7F BD 5F D4 01 00 00 00 00 00 00 00 00 01 00 00 00 02 00 00 00 
Value Type Changed To: REG_BINARY
Key Modified Time 1: 10/9/2018 1:21:12 PM
Key Modified Time 2: 10/9/2018 1:47:40 PM
==================================================`
```

**Comment by Disassembler0** [comment]
The tweak mentions that in the comment note
https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/27157fef8f1be091a3ddc00aca08bdfae2254d60/Win10.psm1#L166

The registry values are taken from [GPOs introduced in 1709](https://docs.microsoft.com/en-us/windows/client-management/new-policies-for-windows-10#new-group-policy-settings-in-windows-10-version-1709).

---

About the values you've found...

The first blob is likely not directly related, as the same registry value is changed by few other services and applications, so it's likely just some common notification store. I see 15 nonconsecutive changes in your data, but I have absolutely no clue what do they mean.

The `StartTime` value is obviously a timestamp, so that can be omitted.

The last short blob is in `bam` service, which is *Background Activity Moderator Driver*, and is likely of no importance either.

The weirdest thing is that if you manually click on the *Activity History* checkboxes, there is no immediate change in registry, so I'm starting to doubt if the setting (and the feature in general) has actually any effect at all without Microsoft account. I'll try to check if there is any difference when I use it, however there isn't much I can do from my position. Yes, the fact that the control stays enabled is a bug... but Microsoft's bug, not mine. :)

**Comment by Disassembler0** [comment]
So. The actual value for the options and for the whole Activity History is stored in file `%LocalAppData%\ConnectedDevicesPlatform\CDPGlobalSettings.cdp`, which is in a freaking JSON format!

There are `"PublishUserActivity"` and `"UploadUserActivity"` values under `"AfcPrivacySettings"` which are controlled by the two checkboxes in settings.

Once I stop crying, I'll try to figure out if it's simple enough to change that value from PowerShell and if it's even worth it.

**Comment by Disassembler0** [comment]
Nope. This isn't the way to go either. The checkboxes control the value in the file but not vice versa. The file can be modified quite easily with

```powershell
$config = "$env:LocalAppData\ConnectedDevicesPlatform\CDPGlobalSettings.cdp"
(Get-Content $config).Replace('"PublishUserActivity" : 1', '"PublishUserActivity" : 0').Replace('"UploadUserActivity" : 1', '"UploadUserActivity" : 0') | Set-Content $config
```

but it doesn't have the desired effect as the values seem to be stored also elsewhere (most likely Cortana Cache DB).

---

There's one more thing I have discovered - The checkboxes are unchecked when the *Connected Devices Platform User Service* is disabled.

```powershell
Stop-Service "CDPUserSvc" -WarningAction SilentlyContinue
Set-Service "CDPUserSvc" -StartupType Disabled
```

I'm not entirely sure if this is correct solution as the CDP encompasses more features than just *Activity History*, e.g. *Shared Experiences*, but the Shared Experiences setting seem to be unaffected by the disabled service, so I'm gonna go ahead and it as part of the `DisableActivityHistory` tweak. Chances are that the people disabling Activity History are disabling also Shared Experiences and if not, then the worst what can happen is that I'll have another issue for this opened soon. (I'm not really willing to test it as I don't want to link any devices to my Microsoft account.)

**Comment by Disassembler0** [comment]
Alright, that makes things even worse (#170, #172). I've reverted the commit 08ce664. I'll rather have documented graphical bug than several unknown functional ones. :)
