### ISSUE TITLE
Chyba ve scriptu

### ISSUE THREAD

**Issue by truefriend-cz** [Disassembler0/Win10-Initial-Setup-Script#15]
Problém ve scriptu. Pokud budete chtít vypnout stisknutí klávesy a restartování tak musíte umazat Auxiliary Functions ale nestačí a nepomůže ani smazání čárky za slovem EnableIEEnhancedSecurity.
Ale je třeba Auxiliary Functions nahradit buď dvouma uvozovkami. Nebo příkazem Exit na konci scriptu s odkazem v začátku scriptu.

	# "DisableCtrlAltDelLogin",     # "EnableCtrlAltDelLogin",
	# "DisableIEEnhancedSecurity",  # "EnableIEEnhancedSecurity",

	### Auxiliary Functions ###
	"WaitForKey",
	"Restart"
)

**Comment by Disassembler0** [comment]
Duplicate of #14
