### ISSUE TITLE
Revert an entire preset

### ISSUE THREAD

**Issue by yassineim** [Disassembler0/Win10-Initial-Setup-Script#161]
How to revert every enabled function in a preset?

**Comment by Disassembler0** [comment]
Create another preset with corresponding revert tweaks and run it. Revert tweaks are those in second column in [Default.preset](https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/master/Default.preset)

**Comment by yassineim** [comment]
Can I do it in some automated way? Because there is a whole lot to uncomment

**Comment by yassineim** [comment]
OK got it, a little of regex and column-selecting did the job.
