### ISSUE TITLE
Language bar dissapears

### ISSUE THREAD

**Issue by dave-cz** [Disassembler0/Win10-Initial-Setup-Script#171]
I'm not sure if it's related with using _Win10-Initial-Setup-Script_ but Language bar dissapears and also (Left Alt + Shift) doesn't work to switch Keyboard Layout. I found solution in comments [here](https://www.intowindows.com/how-to-enable-or-disable-the-language-bar-in-windows-10/#comment-672550):

`Set-WinLanguageBarOption -UseLegacySwitchMode`

**Comment by Disassembler0** [comment]
Did you use the default preset or a custom one? In the default, there are few things related to the notification area, but none of them touches the language bar. Apart from that, there is `AddENKeyboard` which *adds* a layout. If you could give me your preset or steps how to replicate the problem, I might be able to help a bit more.

Also, just to clear a possible issue - if you've applied recent version of the script, run powershell as admin and execute following command
```
Set-Service "CDPUserSvc" -StartupType Automatic
```
and then reboot. I haven't been able to replicate the problem you're describing but this fixes few other desktop-related ones (#170, #172), so maybe it will help even in this case.

**Comment by dave-cz** [comment]
I did use default preset and only make taskbar height bigger to see Date and Time. I have Win 10 Pro Lenovo OEM in English with Czech and US keyboard layout.

After yesterday Windows Update Keyboard Layout dissapears again and neither one of the previous commands works.
