### ISSUE TITLE
How can I re-enable virtual desktops?

### ISSUE THREAD

**Issue by rajlego** [Disassembler0/Win10-Initial-Setup-Script#172]
Win + Tab and Ctrl + Win Left/Right don't work and I can't use virtual desktops now. What flags would let me change back this functionality?

**Comment by Disassembler0** [comment]
Same cause as in #170.

Run powershell as admin and execute following command
```
Set-Service "CDPUserSvc" -StartupType Automatic
```
Then reboot and it will work again.
