### ISSUE TITLE
Quick Access is now missing from Windwos explorer

### ISSUE THREAD

**Issue by tryptc** [Disassembler0/Win10-Initial-Setup-Script#173]
Quick Access is now mussing from Windows Explorer. I have tried a few fixes, including a few registry tweaks to no avail.

**Comment by Disassembler0** [comment]
Well... there's a good chance that tweak named `HideQuickAccess` hides quick access ;)

If you have applied your custom preset, please paste it. Otherwise see question 1 in FAQ and then apply `ShowQuickAccess`.

**Comment by tryptc** [comment]
Thanks! I found it!

Love and Peace!
