### ISSUE TITLE
Adobe Flash compatibility broken.

### ISSUE THREAD

**Issue by wowokaybye** [Disassembler0/Win10-Initial-Setup-Script#176]
After running the script, there is no way to reinstall and re-enable Adobe Flash for Edge. 

![image](https://user-images.githubusercontent.com/45148851/48675949-23835f00-eb60-11e8-8efe-1c2098d194a4.png)

**Comment by Disassembler0** [comment]
Use `EnableAdobeFlash` and read FAQ.

**Comment by wowokaybye** [comment]
I did, but `EnableAdobeFlash` didn't change anything. :/

**Comment by Disassembler0** [comment]
I find that hard to believe because `EnableAdobeFlash` removes the 2 registry keys which `DisableAdobeFlash` sets. Make sure to run the `EnableAdobeFlash` tweak as admin and reboot the computer afterwards (the change is in HKLM hive, which usually takes effect only after reboot)

**Comment by wowokaybye** [comment]
I think I'm not doing it right. Could you help me a second there? Where am I really supposed to put this command in?

**Comment by Disassembler0** [comment]
That's not a command, that's a tweak name. You were supposed to either run the tweak as command line parameter or to create a preset with that tweak, both of which are described in [advanced usage](https://github.com/Disassembler0/Win10-Initial-Setup-Script#advanced-usage).

Easier way for you may be the following:

1. Press Win+R (keyboard shortcut for *Run...* prompt).
2. Type there `regedit` and press enter.
3. Confirm UAC prompt.
4. In the left pane, navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer`.
5. In the right pane, delete value named `DisableFlashInIE`.
6. In the left pane, navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\MicrosoftEdge\Addons`.
7. In the right pane, delete value named `FlashPlayerEnabled`.
8. Close all windows and applications and reboot the computer.
