### ISSUE TITLE
Set taskbar buttons to always combine and hide labels AGAIN

### ISSUE THREAD

**Issue by d-wendel** [Disassembler0/Win10-Initial-Setup-Script#180]
Win10 1809, Taskbar combine settings seem to not work. Any change I make results in "display all taskbar icons".  Does any other setting affect this one?

**Comment by Disassembler0** [comment]
Are you referring to `SetTaskbarCombineWhenFull` / `SetTaskbarCombineNever` / `SetTaskbarCombineAlways` ? Because I've just tried them on 1809, build 17763.107 and they all work as expected. There wasn't a change in these since Windows 7. Can you please describe step by step what are you doing?

**Comment by Disassembler0** [comment]
I suspect that there might be a confusion of terms. "*right side taskbar icons*" doesn't make sense - do you have in mind the icons next to the clock (volume, network etc.)? If so, then we're talking about *systray* or *notification area* in which case you want to apply `HideTrayIcons` tweak.

**Comment by d-wendel** [comment]
I can't believe I missed something so darn simple, you are correct.
Combine icons when taskbar is full from running programs. (usually starting from the left side)
Notification area icons all showing is what I was referring too.  It's fixed.
Great and helpful responses though! Keep up the excellent work.
