### ISSUE TITLE
Continued Maintenance  

### ISSUE THREAD

**Issue by mscreenie** [Disassembler0/Win10-Initial-Setup-Script#19]
> Q: For how long are you going to maintain the script?
> A: As long as I use Windows 10.

Thank you for making this and maintaining. It's made my switch to Win 10 bearable. I've tried holding out switching from Win 7 for as long as I could and I've used your script on about 5 machines. 

I run Windows update manually and have it disabled otherwise. I also use your script with https://github.com/crazy-max/WindowsSpyBlocker and block all MS IP's, domains on every level and stack.

Would be nice to see a donate method to show extended appreciation. Thanks.

**Comment by Disassembler0** [comment]
Glad you like the script. The best kind of donation would be to help me develop the script even further as there are still few things worth automation. But I guess you're talking about different kind of donation :) In such case, feel free to use this [PayPal link](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=disassembler%40dasm%2ecz&item_name=Disassembler&no_shipping=1). I'll add it also to the FAQ. Thanks for suggestion.

**Comment by mscreenie** [comment]
Yes. I can contribute to this project, I work with PS a fair amount. If I see anything I can add I'll contribute. Thank you.
