### ISSUE TITLE
Disable swapfile.sys

### ISSUE THREAD

**Issue by Disassembler0** [Disassembler0/Win10-Initial-Setup-Script#190]
Request received via mail.

> ```
> # Enable SWAP File
> Function EnableSwapFile {
>     Write-Output "Enabling SWAP File..."
>     Remove-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" -Name "SwapfileControl" -ErrorAction SilentlyContinue
> }
> 
> # Disable SWAP File
> Function DisableSwapFile {
>     Write-Output "Disabling SWAP File..."
>     Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" -Name "SwapfileControl" -Type Dword -Value 0
> }
> ```

As a side note - this isn't swap per se. This is just swapfile.sys used for suspended Modern UI applications. The *real* swap in pagefile.sys is unaffected by this tweak.

**Comment by AzimsTech** [comment]
What are the benefits and disadvantage of disabling this?

**Comment by Disassembler0** [comment]
I'd say no benefits and no disadvantages provided you have sufficient hardware. :)

What it does is that it removes the hidden system swapfile.sys file which always has 256 MB in size and which is used to swap out suspended processes of Modern UI apps and Windows components such as Start menu, Cortana, Store etc. if the need arises. If this tweak is applied, you get extra 256 MB disk space free in exchange for not being able to swap out a bunch of processes occupying roughly the same size in RAM, depending on how many Modern UI apps you use (there is bunch of other tweaks which reduce them only to those which are really necessary).

I can imagine this tweak being used on systems with ridiculously small SSDs (<128 GB) and by people who absolutely want to get rid of every extraneous part of system. Other that that, it doesn't really help, but it doesn't harm either.

**Comment by AzimsTech** [comment]
Nice! Thanks for the clear explanation.
