### ISSUE TITLE
KMS client activation data

### ISSUE THREAD

**Issue by wallrik** [Disassembler0/Win10-Initial-Setup-Script#195]
This doesn't really apply to home users since they don't use KMS activation, but I figured maybe it could still be included in this script, because I use it myself. 😸 

[Turn off KMS Client Online AVS Validation](https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.SoftwareProtectionPlatform::NoAcquireGT)

> This policy setting lets you opt-out of sending KMS client activation data to Microsoft automatically. Enabling this setting prevents this computer from sending data to Microsoft regarding its activation state.
If you disable or do not configure this policy setting, KMS client activation data will be sent to Microsoft services when this device activates.

I haven't done any tests to see if this is affected if you have already disabled telemetry, but I just end up setting it to be safe 😆

**Comment by Disassembler0** [comment]
Doesn't KMSAuto / KMSpico set this automatically? 😛

On more serious note, before I delve to any research - Do you know if disabling this affects the licensing or activation anyhow? Or is it just another metadata collection without any effect for the user?

**Comment by wallrik** [comment]
> Doesn't KMSAuto / KMSpico set this automatically? 😛

Hehe, I don't know. I don't use those tools. But I wouldn't count on them doing it actually.

> On more serious note, before I delve to any research - Do you know if disabling this affects the licensing or activation anyhow? Or is it just another metadata collection without any effect for the user?

Activation is fine. I've used it at work for years. But I can't say for sure what Microsoft thinks about it. I just figured they put the option there for organizations that don't want to send data back to MS. I never asked 😆

**Comment by CHEF-KOCH** [comment]
You can disable it and use HWIDGEN instead which does not even connect to the internet at all.

Even on a legitimate system this can be turned off because AVS Validation is a part of the telemetry process to solve possible "activation problems".
