### ISSUE TITLE
Media keys disabled

### ISSUE THREAD

**Issue by peterjohansen** [Disassembler0/Win10-Initial-Setup-Script#2]
Hey. Great script! It's exactly what I've been looking for.

I ran it today (slightly modified from the default) and everything worked great, but after the restart the media keys on my keyboard stopped working. I got it working again with [these instructions](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Bug-Report-Spotify-has-issues-dealing-with-media-keys-and/m-p/583084/highlight/true#M66153), but it would be great if the issue could be avoided from the start.

I'm not sure what caused the problem. I did not run it with the _UninstallMediaPlayer_ preset and I can't see any other presets that would interfere (maybe one of the bloatware apps?). Do you know what could cause it?

**Comment by Disassembler0** [comment]
Can't reproduce on clean Ent and Pro build 14393.693 VMs and neither on any of my installations where I use multimedia keyboards (Logitech). Moreover I don't see a reason why would UPnP service create any interference with multimedia keys. I suspect some software issue on your side. Can you re-enable it and check if the issue persists with all multimedia players? (WPM, VLC, Foobar2000 or any other of your choice)

**Comment by peterjohansen** [comment]
I enabled it again and restarted my computer. The keys still work. Weird. I tested it with Spotify and VLC. It definitely stopped working after running the script, though. Feel free to close the issue if you think the cause lies elsewhere.
