### ISSUE TITLE
Disable AutoLogger using registry

### ISSUE THREAD

**Issue by NuttuN** [Disassembler0/Win10-Initial-Setup-Script#20]
Hello,
Is there a reason why AutoLogger is disabled by removing AutoLogger file and restricting directory instead of editing registry?
HKLM\SYSTEM\ControlSet001\Control\WMI\Autologger\AutoLogger-Diagtrack-Listener\Start: 0x00000000
HKLM\SYSTEM\CurrentControlSet\Control\WMI\Autologger\AutoLogger-Diagtrack-Listener\Start: 0x00000000

**Comment by Disassembler0** [comment]
According to various documentations (eg. [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363687(v=vs.85).aspx)), the `Start` key only affects the next boot and does not persist.

But I'm a bit confused now as I wanted to test it and I'm not able to get my clean Win10 Pro 1703 (build 15063.540) to even create the `AutoLogger-Diagtrack-Listener.etl` file, let alone log anything into it. I'll try to check it later but there is a slight possibility that Microsoft changed its behaviour in one of previous build.

**Comment by Disassembler0** [comment]
Okay, so I confirm that the `Start` key only applies for next boot. And I also confirm that the `AutoLogger-Diagtrack-Listener.etl` is not created automatically on new builds (1607 and newer), so I'm leaving the tweak just for historical builds.
