### ISSUE TITLE
Game Mode

### ISSUE THREAD

**Issue by AnubisMann** [Disassembler0/Win10-Initial-Setup-Script#205]
Hi

I request to add a line in the script to deactivate the game mode.

Thanks.

**Comment by Disassembler0** [comment]
That should be already covered by `DisableXboxFeatures` tweak.

**Comment by AnubisMann** [comment]
> That should be already covered by `DisableXboxFeatures` tweak.

It does not work that way. 
In Windows 10 1809 for more than disable Xbox with the script ...... in the Windows settings> Games> Game mode is still activated and you have to press the button to deactivate it.
A line in the script is required so that the game mode appears disabled in the Windows settings. In version 1809 they modified those options and you will see them in a different way.

**Comment by Disassembler0** [comment]
Ah. Nice. I wasn't aware that it can be disabled from 1809 onwards. This does the trick:
```powershell
Set-ItemProperty -Path "HKCU:\Software\Microsoft\GameBar" -Name "AutoGameModeEnabled" -Type DWord -Value 0
```
Unfortunately it needs to be applied on per-user basis as there is no GPO for this. I'm not even surprised.

I'll add it to `DisableXboxFeatures` shortly.
