### ISSUE TITLE
Full Screen Optimization

### ISSUE THREAD

**Issue by AnubisMann** [Disassembler0/Win10-Initial-Setup-Script#209]
Tweak for video game users: Disable full screen optimization
Steps:

HKEY_CURRENT_USER\System\GameConfigStore

Create a new 32-bit DWORD value called GameDVR_DSEBehavior

Assign 2 to turn off full-screen optimizations or 0 to enable them

**Comment by Disassembler0** [comment]
Can it be merged with `DisableXboxFeatures` tweak? There is already something related to `GameConfigStore` key and `*GameDVR*` values. I would even think that when the DVR is disabled completely, the full-screen optimization is disabled too. Or is it worth to have it as separate tweak?
