### ISSUE TITLE
Running as a GPO

### ISSUE THREAD

**Issue by jcfrazier6** [Disassembler0/Win10-Initial-Setup-Script#214]
How do you set this script up to run as a Group Policy Object when the user logs on? I have tried several ways but no luck...

**Comment by Disassembler0** [comment]
There are some hints on usage in multiuser environment here - https://github.com/Disassembler0/Win10-Initial-Setup-Script/issues/29#issuecomment-333040591.

In domain environments, I suggest using the *actual* GPOs and push the rest of the registry keys for which there are no GPOs like [this](https://thesolving.com/server-room/how-to-deploy-a-registry-key-via-group-policy/).
