### ISSUE TITLE
Microsoft apps from Win8.1

### ISSUE THREAD

**Issue by r3incarnat0r** [Disassembler0/Win10-Initial-Setup-Script#218]
After running UninstallMsftBloat, there are still 8.1-specific MS apps left in case Windows 10 was upgraded from Windows 8.1 (such as Microsoft.Reader). I could eventually make a PR to cover them, but before I spend the time with it, I need to ask if such update is even wanted and would be merged.

**Comment by Disassembler0** [comment]
I claim that I consider freshly installed system from MSDN as the default, but I have already merged several (yours :) ) PRs with some Lenovo and HP proprietary bloatware, where I had much bigger doubts. So yes, go for it. Thanks.

**Comment by r3incarnat0r** [comment]
I PRed my findings from both clean VM test and wilderness sightings as an addition to #208.
