### ISSUE TITLE
return the icon

### ISSUE THREAD

**Issue by userosos** [Disassembler0/Win10-Initial-Setup-Script#219]
How i can return the icon, please?
![default](https://user-images.githubusercontent.com/22872748/53303224-00f89480-3879-11e9-8ebf-bb229f11a684.png)

**Comment by Disassembler0** [comment]
Below is a screenshot of how the systray looks like after a fresh installation. Yours is laptop/tablet, so it has extra battery and touchpad icons. Which icon do you have in mind?
![vystrizek](https://user-images.githubusercontent.com/5568046/53303307-309fa080-3869-11e9-8dde-9592cd450d43.PNG)

**Comment by userosos** [comment]
I have an PC. I mean arrow.

**Comment by userosos** [comment]
Screen from my PC:
![image](https://user-images.githubusercontent.com/22872748/53303441-5635a580-387b-11e9-97f1-866d34ce6910.png)

**Comment by Disassembler0** [comment]
Aaa, ok, I thought that's a screenshot of your current desktop.

`ShowTrayIcons` / `HideTrayIcons` tweaks affect this. `ShowTrayIcons` is included in the default preset and causes the notification area (SysTray) icons to be visible at all times. So to get the arrow back either apply `HideTrayIcons` tweak or simply fix it manually by using the checkbox in *Settings* -> *Personalization* -> *Taskbar* -> *Select which icons appear on the taskbar* -> *Always show all icons in the notification area*

**Comment by userosos** [comment]
It is not work for me:
![image](https://user-images.githubusercontent.com/22872748/53303577-1a034480-387d-11e9-8e8e-4c9890868e3a.png)
Sorry for russian language.

**Comment by Disassembler0** [comment]
Hm, yes. I forgot that even though the registry value is in HKCU, it comes from a GPO and overrides whatever is set manually. So in that case you need to run `HideTrayIcons` as admin. Alternatively, you can do following:

1. Open regedit
2. Navigate to `HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer`
3. Delete `NoAutoTrayNotify` value
4. Log off and then log back in

**Comment by userosos** [comment]
@Disassembler0 
Big thx! it is work!
