### ISSUE TITLE
[KiND QUESTiON] Feedback in RS5 not removable?

### ISSUE THREAD

**Issue by github-tomster** [Disassembler0/Win10-Initial-Setup-Script#222]
hello world

on RS5 ENTERPRiSE S (LTSC)
Function DisableFeedback is applied
but, on startmenu there is still the 'Give Feedback' button available...
seems that this is something totally different, isnt it?
how do i get rid of this and how can i prevent users sending screenshots to m$?

**Comment by Disassembler0** [comment]
`DisableFeedback` stops the occasional Windows popup asking for an opinion on handling, look and feel and general usability of the OS and its applications. The corresponding controls are in *Settings* -> *Privacy* -> *Diagnostics & feedback*. It's just to make the system less obtrusive, but if the users *want* to send a feedback, they still can.

If you're referring to the *Provide feedback* feature of the start menu search on the screenshot below, then it can't be removed as it's part of the Cortana application. So to get rid of it, you'd also need to completely sacrifice start menu search and probably some other features.

![Provide feedback](https://social.technet.microsoft.com/Forums/getfile/830228)

> and how can i prevent users sending screenshots to m$

You can try blocking Cortana in firewall. There is already a rule called *Cortana* with all the application packages and services predefined, which is allowed by default. Alternatively, you can try finding out and blocking the hostnames which it tries to connect to. **Disclaimer:** These are just ideas how I would try to approach the problem. I haven't actually tested either of these and I'm not planning to.

**Comment by github-tomster** [comment]
@Disassembler0 
roger that!
seems to stay a PiTA, well...
at least i am now sure it is a different function/feature
so sad what happend to the OSs nowadays and thank you for the scripts!
