### ISSUE TITLE
Chocolatey package - enhancement

### ISSUE THREAD

**Issue by dhoer** [Disassembler0/Win10-Initial-Setup-Script#23]
What are your thoughts to making a choco package?  e.g., 

### preset
```
choco install win10setup --force
```
or
```
choco install win10setup --params "'/ApplyAll'" --force
```

### custom
```
@"
# Security tweaks
EnableFirewall
EnableDefender

# UI tweaks
ShowKnownExtensions
ShowHiddenFiles
"@ > ./mypreset.txt
choco install win10setup --params "'/Custom:./mypreset.txt'" --force
```

### alacarte
```
choco install win10setup --params "/EnableFirewall /EnableDefender" --force
```

### preset with alacarte
```
choco install win10setup --params "/ApplyAll /EnableFirewall /EnableDefender" --force
```

### custom with alacarte
```
@"
# Security tweaks
EnableFirewall
EnableDefender

# UI tweaks
ShowKnownExtensions
ShowHiddenFiles
"@ > ./mypreset.txt
choco install win10setup --params "/Custom:./mypreset.txt /EnableFirewall /EnableDefender" --force
```

### restore
```
choco install win10setup --params "/RestoreAll" --force
```

---
This totally abuses chocolatey, but would make it simple for users to copy, customize,  and place in their private nuget server.   

If you are interested and want a PR, let me know.  Thanks.

**Comment by dhoer** [comment]
You could also run preset, custom and alacarte.  They would run in that order or precedence.

**Comment by dhoer** [comment]
I wrapped this in a choco package: https://github.com/dhoer/choco-win10-initial-setup-script

Feel free to use it.  Thanks for this awesome script!  I was struggling to find figure out how to disable windows functions.

**Comment by Disassembler0** [comment]
OK, I gotta plead ignorance here. I'm aware that chocolatey is some package manager for people who are too sexy to search for silent installation switches themselves. I have never used and I'm not planning to. What's the benefit of having this script in such repository if the simplest 'get & run' can be achieved with this?

```powershell
Invoke-WebRequest https://raw.githubusercontent.com/Disassembler0/Win10-Initial-Setup-Script/master/Win10.ps1
powershell.exe -NoProfile -ExecutionPolicy Bypass -File Win10.ps1 <your options here>
```

The aim of the script is to adjust the system once, immediately after the installation. And in worst case re-adjust it after some major OS update. If I'm understanding the concept of chocolatey correctly, it would mean that the script would get re-applied with every release, resp. whenever there is a new release and the user launches upgrade. That would also mean that the user has to re-adjust the preset with every upgrade as they might not be compatible between the versions.

Don't get me wrong, I'm not against the idea (actually I am, but only if it gets complicated). I'm just not sure if it's worth the hassle. What would be the minimum viable code to get chocolatey working without changing anything in the original script? Would this work?

```powershell
$pdir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
$pp   = Get-PackageParameters

if ($pp["custom"] -ne $null -and $pp["custom"] -ne '') {
    Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File `"$pdir\Win10.ps1`" $($pp['custom'])" -WorkingDirectory $pwd -Verb RunAs
}
```

And launch with original syntax like this?

```
choco install win10setup --params "/Custom:EnableFirewall EnableDefender" --force
choco install win10setup --params "/Custom:-preset mypreset.txt" --force
```

Btw. looking at your repo... it's not a good idea to use the *ApplyAll* and *RestoreAll* presets. Those should be just for testing.

**Comment by dhoer** [comment]
> What's the benefit of having this script in such repository if the simplest 'get & run' can be achieved with this?

I agree somewhat. But it is nice to have a consistent way to manage installs for many customer that all have different needs.  If chocolatey would implement this: https://github.com/chocolatey/choco/issues/1390. Then the advantage would be automatic cache of download url.  Which would mean that I would never have to worry if I'm cutting a new windows AMIs and github or whatever is down.  

> What would be the minimum viable code to get chocolatey working without changing anything in the original script? Would this work? And launch with original syntax like this?

I don't think it would handle the spaces. And I had issues with choco running the script directly as well, so I pulled out the functions, then sourced the functions, and run iex within choco. Maybe if there were a way to pull out the tweak section and functions after choco downloads, that would work.  But would we would have to agree on begin and end comments not changing for both tweaks and function sections so I can pull those out to their own files during choco install.  

So tweaks would pull everything between `# Default preset` and `# Privacy Settings`, and functions would pull everything between `# Privacy Settings` and `# Parse parameters and apply tweaks`. 

> Btw. looking at your repo... it's not a good idea to use the ApplyAll and RestoreAll presets. Those should be used just for testing.

Good to know. 

I also like the idea of being able to run /preset /customer and zero or many /<functions> tags altogether.  Precedence would be that order as well. So if preset was set, it would always run first, custom - if set- second, and <functions> last. But I can't guarantee the order <functions> will run, but it shouldn't matter.

**Comment by dhoer** [comment]
I'm going to go ahead and close this.
