### ISSUE TITLE
How can I undo this?

### ISSUE THREAD

**Issue by edjalmobf** [Disassembler0/Win10-Initial-Setup-Script#230]
I know that have this in discription

> Q: I've run the script and it did something I don't like, how can I undo it?
> A: For every tweak, there is also a corresponding function which restores the default settings. The default is considered freshly installed Windows 10 or Windows Server 2016 with no adjustments made during or after the installation. Use the tweaks to create and run new preset. Alternatively, since some functions are just automation for actions which can be done using GUI, find appropriate control and modify it manually.

but I don't know how do this.
Can you help me?

**Comment by Disassembler0** [comment]
Which tweak in particular do you wish to undo?

**Comment by edjalmobf** [comment]
Is quick access shortcuts of explorer. I really miss that!

Now I just want this, but if someday I want to undo another thing, how I do this?

**Comment by Disassembler0** [comment]
Assuming you haven't made any customization, [Default.preset](https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/master/Default.preset) is the preset file which is used when you run the script. In this file you can see which tweaks are applied (first column, lines **not** starting with `#`) and you can find the corresponding functions in the [Win10.psm1](https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/master/Win10.psm1) tweak library. In the second column, there are tweaks which revert whatever the first column did, so you just need to create a preset using the revert tweaks and run it. Alternatively, you can apply the tweaks directly from command line as described in [Advanced usage](https://github.com/Disassembler0/Win10-Initial-Setup-Script#advanced-usage).

For restoring the Quick Access shortcuts you probably want to run something like this in a directory where you have downloaded the files.
```
powershell.exe -NoProfile -ExecutionPolicy Bypass -File Win10.ps1 -include Win10.psm1 RequireAdmin ShowQuickAccess
```

**Comment by edjalmobf** [comment]
Thanks! Worked! :)

I think now I know how create a preset (like explaned in [Advanced usage](https://github.com/Disassembler0/Win10-Initial-Setup-Script#advanced-usage)).
But if I can suggest something is create a file that users can choose option when execute it!

Like this: 
```
show function
yes (disable) no (keep)
```
I think this is good for not advanced users.

Thanks for this script and for this help too!
