### ISSUE TITLE
Add wallPaper

### ISSUE THREAD

**Issue by vince50** [Disassembler0/Win10-Initial-Setup-Script#235]
it is possible to add a line to put a wallpaper on the desktop?

**Comment by Disassembler0** [comment]
You can create a custom tweak with path to your preferred wallpaper. Something like
```
Function SetWallpaper() {
    Set-ItemProperty -Path "HKCU:\Control Panel\Desktop\" -Name "Wallpaper" -Type String -Value "X:\Some\Image.png"
    rundll32.exe user32.dll, UpdatePerUserSystemParameters
}
```

Check [Advanced usage](https://github.com/Disassembler0/Win10-Initial-Setup-Script#advanced-usage) in FAQ to see how to work with custom tweaks and presets.
