### ISSUE TITLE
pin iexplorer only on a taskbar

### ISSUE THREAD

**Issue by vince50** [Disassembler0/Win10-Initial-Setup-Script#236]
adding ieplorer in the taskbar

**Comment by Disassembler0** [comment]
This isn't a setting offered by the basic system, this is already an extra customization which creates something new, so I would suggest creating a custom tweak for this too. (See again [Advanced usage](https://github.com/Disassembler0/Win10-Initial-Setup-Script#advanced-usage) in FAQ on how to work with custom tweaks and presets). However pinning/unpinning is a bit problematic. You can read about this in #8 and #147.

For iexplore in particular, the tweak would look like
```powershell
Function PinIExplore {
    # Bring pinning / unpinning handler into '*' class scope
    $pinHandler = Get-ItemPropertyValue -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\Windows.taskbarpin" -Name "ExplorerCommandHandler"
    New-Item -Path "HKCU:Software\Classes\*\shell\pin" -Force | Out-Null
    Set-ItemProperty -LiteralPath "HKCU:Software\Classes\*\shell\pin" -Name "ExplorerCommandHandler" -Type String -Value $pinHandler

    # Pin iexplore.exe
    $item = Get-Item "$($env:ProgramFiles)\internet explorer\iexplore.exe"
    $item = (New-Object -Com "Shell.Application").Namespace($item.DirectoryName).ParseName($item.Name)
    $item.InvokeVerb("pin")

    # Remove the handler
    Remove-Item -LiteralPath "HKCU:Software\Classes\*\shell\pin" -Recurse
}
```
but for the reasons given above, I'm not gonna add it to the basic tweak library.

**Comment by Lastwish90** [comment]
Does the above function to Pin iexplorer on taskbar currently work on W10? Or has it been blocked by MS?
