### ISSUE TITLE
Traduction en français

### ISSUE THREAD

**Issue by stepmond** [Disassembler0/Win10-Initial-Setup-Script#237]
Etes vous intéressé par un tutoriel en français qui détail toutes les options?
Pour l'instant j'ai mis le didacticiel sur mon site mais si c'es trop commercial je peux modifier:
[https://www.pcsoleil.fr/optimisation-de-windows-10-grace-a-win10-initial-setup-script/](url)

**Comment by malexxx** [comment]
Merci pour la trad.

I vote on !

**Comment by stepmond** [comment]
De rien! dommage je ne suis pas sûr qu'un wiki officiel soit au programme; le script est fait pour les utilisateurs avertis, censés connaitre les optimisations

**Comment by malexxx** [comment]
Effectivement

**Comment by c-rilaun** [comment]
Bonjour bonjour,

Je pense qu'un bout de wiki reste utile même pour les utilisateurs avertis. J'ai beau être sysadmin depuis plus de 3 ans, je ne me rappelle pas par cœur de toutes les fonctionnalités Windows et de ce qu'elles font.

Il peut être bien d'attendre la version 4 toutefois, au vu des modifications qui seront apportées.

**Comment by stepmond** [comment]
en effet, en tout cas j'ai remise à jour mon tuto en Francais, et suivi les évolutions du script
https://github.com/Disassembler0/Win10-Initial-Setup-Script/issues/url

**Comment by AnErrupTion** [comment]
Sympa, mais faudrait carrément mettre en français le script, si tu vois ce que jveux dire
