### ISSUE TITLE
Disable Windows Ink Workspace suggestions

### ISSUE THREAD

**Issue by tylerfilla** [Disassembler0/Win10-Initial-Setup-Script#246]
I have a suggestion for a tweak.

Windows tries to suggest stylus-friendly apps in the Windows Ink Workspace. I think it would be helpful to add a tweak to the script that disables this. The suggestions are toggled in the Settings app which appears to set the ```DWORD``` value ```PenWorkspaceAppSuggestionsEnabled``` on the key ```HKCU:\Software\Microsoft\Windows\CurrentVersion\PenWorkspace```. A value of ```1``` means enabled, and a value of ```0``` means disabled.

Also, if we delete the value entirely, the Settings app reports that suggestions are back enabled. Perhaps the tweak should check for the existence of ```PenWorkspaceAppSuggestionsEnabled``` before setting it, as AFAIK this could be the freshly-installed default.

Thanks for the useful script!

**Comment by tylerfilla** [comment]
One more thing, I'm not exactly certain what category this hypothetical tweak would fall under. If data collection is involved to form the suggestions, then it's a privacy tweak of course. But, it could just be a random selection of apps deemed pen-friendly. Maybe a Google search could clear this up if it's that important 😅

**Comment by Disassembler0** [comment]
Okay. I have 3 touch devices available, all of them on 1903 (18362.329) and on all of them I have different items and checkboxes in the settings. I have no idea where is the setting you talk about, but I believe you that there is one. :)

There is even a group policy *Allow suggested apps in Windows Ink Workspace* under *Windows Components\Windows Ink Workspace* which sets DWord `AllowSuggestedAppsInWindowsInkWorkspace` under `HKLM\SOFTWARE\Policies\Microsoft\WindowsInkWorkspace`.

So if this is really only about suggesting mostly unwanted apps, then the best fit would likely be as part of already existing `DisableAppSuggestions`. What do you think?

**Comment by tylerfilla** [comment]
Sorry, but I meant to say something here about this in the past weeks. It looks like Windows Ink Workspace got a makeover in the meantime. Instead of a big pane with an area for app suggestions near the bottom (as seen in [this tiny image](https://msegceporticoprodassets.blob.core.windows.net/asset-blobs/28718_en_4)), it's been reduced to a small toolbar with a few buttons. I actually quite liked the sketchpad feature, but oh well. There are no longer any app suggestions, and the checkbox was removed from Settings.

I think it would have fit well under `DisableAppSuggestions`. I'll leave this issue open in case you still want to do something about it, but I have no need for this feature anymore.

Thanks again!

([related question online](https://answers.microsoft.com/en-us/windows/forum/all/windows-ink-workspace/87896368-ca43-4d88-8977-a3a3d2b24477))
