### ISSUE TITLE
How do I enable or disable settings

### ISSUE THREAD

**Issue by bluefiberbread** [Disassembler0/Win10-Initial-Setup-Script#251]
Do I add # to disable a function or do I have to remove the entire function?

**Comment by Disassembler0** [comment]
It's enough to comment the function in a preset. See [Advanced usage - presets](https://github.com/Disassembler0/Win10-Initial-Setup-Script#presets)

**Comment by bluefiberbread** [comment]
It looks like this when I want to disable background application access. 
https://i.imgur.com/6U3XN3k.jpg

Is that intended

**Comment by Disassembler0** [comment]
That's not the file you should be editing. You most likely want to edit only the `Default.preset` file and comment the line with `DisableBackgroundApps` by prepending `#` sign . I suggest you read the docs I linked above.

**Comment by bluefiberbread** [comment]
Yup that makes sense.
Include it in "Usage" too
