### ISSUE TITLE
DisableMicrophone option

### ISSUE THREAD

**Issue by mpgr04** [Disassembler0/Win10-Initial-Setup-Script#253]
It would be nice to have an option which works the same way as DisableCamera, but for the microphone

**Comment by c-rilaun** [comment]
As i remember, there is a different GUID per mic. 
So either we disable all the mic entry in **HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\MMDevices\Audio\Capture** or completely disable by another option (which i don't know except the one in GUI).

The first option is kinda tricky 'cuz you'll need to modify the device state of all the GUID is reg hive i've specified. 
So it should be something like : 
- List all GUID and save them in a value (like **Get-ChildItem -Path Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\MMDevices\Audio\Capture\ | Select-Object Name**)
- Modifiy registry for all $MicGUID, Set DeviceState value to 10000001 in hexadecimal to disable the device. 
_No further modification should be done i guess._
