### ISSUE TITLE
RequireAdmin passes incorrect $args

### ISSUE THREAD

**Issue by akbyrd** [Disassembler0/Win10-Initial-Setup-Script#26]
When I use RequireAdmin in a preset file it looks like the args array being passed to the elevated instance is empty. I'm guessing $args in this case contains the arguments to the RequireAdmin function, not the arguments to the script. This causes the new, elevated Powershell instance to lose track the desired presets and apply the defaul tweaks.

Steps to repro:
Create preset.txt with
    RequireAdmin
    DisableTelemetry
Open a non-elevated cmd or powershell instance.
Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -File Win10.ps1 -preset preset.txt"
Notice default tweaks are being applied.

Thanks for the script. It's super helpful.

**Comment by Disassembler0** [comment]
Really nice bug report for such a stupid mistake :) Thanks.
