### ISSUE TITLE
Help with registry info: In 1903, how to reduce/eliminate fade time when doing screen capture

### ISSUE THREAD

**Issue by HarjitSi** [Disassembler0/Win10-Initial-Setup-Script#260]
Not an issue with the script but I'm hoping you know about how to do this and will add the capability.

Thanks.

**Comment by c-rilaun** [comment]
Hi @HarjitSi ,
First of all, before a thanks there is a question with a please.
Yeah, some users probably know about this capability, but what is your issue ? Could you be more precise ? 
I don't have any fade time when doing screenshot.

But with the snipping tool on W10, you could add delay, is this what you're talking about ? (Ref : 
 [https://www.cnet.com/how-to/windows-10-snipping-tool-delay-capture-pop-up-menus/])

Reach back to us with a real question and not a 'google me this pls suka'.

**Comment by c-rilaun** [comment]
I don't have this issue on my personnal computer. I don't have it also on my pro computer. 
I ran a VM last night (fresh install of w10.1903) and didn't have the issue. 

I guess you are not on a fresh install of 1903 but an updated one. This could be related to that. 

What you can try is the following : 
- Launch Powershell as an admin and type the following one : Get-AppxPackage *Microsoft.ScreenSketch* -AllUsers | Remove-AppxPackage

This will delete ScreenSketch. After that, reboot, and then try reinstall this feature with Microsoft Store (you don't need an account for that, it will ask you to login but you can say 'No thanks').

To find it in Microsoft Store, you have to look for 'Snip & Sketch'.
I just try it, and it works. 

Second solution : use alternative software like greenshot.

**Comment by Disassembler0** [comment]
There isn't any setting for the fade-in/fade-out delay, that's baked in in the application. The old *Snipping tool* and the new *Snip & Sketch* are two entirely different applications, so the behavior is also different. I find the fade-in also unnecessary, however traditionally, if you want instant screenshots, you use *print screen* key.

Feel free to send a feedback about this to Microsoft via the feedback feature.
