### ISSUE TITLE
Task bar issue with last update Windows 10 "18362.329"

### ISSUE THREAD

**Issue by AnubisMann** [Disassembler0/Win10-Initial-Setup-Script#262]
After applying the script with the latest update of Windows 10, 18362.329, the windows search found in the taskbar stops working. Searching with the magnifying glass found in the taskbar does not work.

**Comment by KedarWolf** [comment]
Might need to do in the 'Default,preset'
EnableWebSearch
EnableCortana

if you already disabled them use:

EnableWebSearch
EnableCortana

**Comment by AnubisMann** [comment]
> Might need to do in the 'Default.preset'
> EnableWebSearch
> EnableCortana

Before the 329 update everything was working fine, it is a mistake now and always uses Cortana deactivated without problems.

**Comment by KedarWolf** [comment]
Try just enabling WebSearch but with .329 they changed how Contana works and you may need to do both.

**Comment by AnubisMann** [comment]
> WebSearch

Enable WebSearch with Cortana disabled........ works fine. Thanks !

**Comment by LiBOSS-CZ** [comment]
Works for me as well.

**Comment by Disassembler0** [comment]
This seems like a bug in Windows. There's a [thread on reddit](https://www.reddit.com/r/Windows10/comments/cxmot9/windows_10_1903_update_18362329_causes_high_cpu/eyotp50/) about a related problem with high *SearchUI.exe* CPU usage on 18362.329 with [attached fix](https://drive.google.com/uc?id=18udlbgBakZO-9uEuzkh5gq-uKykWugT7&export=download). The fix replaces Cortana cache with a clean one and works also as a fix for the problem described in this issue.

At first glance it's rather elaborate, but I'll check if I can incorporate it somehow or find another (more primitive but simpler) way of fixing it.

**Comment by Disassembler0** [comment]
Also [here](https://twitter.com/WindowsUpdate/status/1168948885076815873) is a tweet from Microsoft acknowledging the problem (though it's still not listed in known issues of [KB4512941](https://support.microsoft.com/en-us/help/4512941/windows-10-update-kb4512941)), and [here](https://borncity.com/win/2019/09/03/windows-10-v1903-ms-investigating-the-search-cortana-issue-09-03-2019/) is a nice writeup about what the bug does and how it can be worked around.

**Comment by Disassembler0** [comment]
One of the "primitive but simple" approaches could be simply copying the old version of cache from WinSxS like this

```
takeown /F C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\cache /A /R
icacls C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\cache /grant Administrators:F /T
robocopy /MIR C:\Windows\WinSxS\amd64_microsoft-windows-c..che.desktop.cortana_31bf3856ad364e35_10.0.18362.1_none_943212ff8fbbe626 C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\cache\Desktop
robocopy /MIR C:\Windows\WinSxS\amd64_microsoft-windows-c..cal.desktop.cortana_31bf3856ad364e35_10.0.18362.1_none_c340725fc95811bb C:\Windows\SystemApps\Microsoft.Windows.Cortana_cw5n1h2txyewy\cache\Local\Desktop
```

However this leaves the whole cache directory with wrong permissions, so it's definitely not ideal and I still recommend using the [fix above](https://drive.google.com/uc?id=18udlbgBakZO-9uEuzkh5gq-uKykWugT7&export=download) instead.

As this is definitely up to Microsoft to fix, I'll just comment this tweak in the default preset and add a note and a warning for 18362.329 users. This won't help those which have already applied it, but I don't think I can do more at this point. Hopefully it'll be fixed one day. I somehow doubt they'll manage it until the next patch tuesday, which is next week.

**Comment by Disassembler0** [comment]
[KB4512941](https://support.microsoft.com/en-us/help/4512941/windows-10-update-kb4512941#section-3) now lists the issue in known issues.

Symptom | Workaround
-- | --
Microsoft is getting reports that a small number of  users may not receive results when using Windows Desktop Search and may  see high CPU usage from SearchUI.exe. This issue only occurs on devices that have disabled searching the web using Windows Desktop Search. | We are working on a resolution and estimate a solution will be available in mid-September.

**Comment by Disassembler0** [comment]
Fixed in [KB4515384](https://support.microsoft.com/en-us/help/4515384/windows-10-update-kb4515384#section-2). I'm impressed.

**Comment by AnubisMann** [comment]
> ![image](https://user-images.githubusercontent.com/15828888/64840225-a9f3ba80-d624-11e9-9127-9085d46a0b81.png)
> 
> as I used fix Cortana cache before the update KB4515384 was applied search working
> Now after the update, KB4515384 has applied search have the problem again what can I do now?

Edit Default.preset with "EnableWebSearch" and "DisableCortana" in Privacy Tweaks. 
I use Notepad++ for edit.

**Comment by iamteerawut** [comment]
> This is probably the most generic advice ever, but try running
> 
> ```
> dism /Online /Cleanup-image /Restorehealth
> sfc /scannow
> ```
> 
> as described [here](https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system). The point is to try and force Windows to restore the Cortana cache using the correct files from WinSxS.

after run this now search working again Thank
