### ISSUE TITLE
Windows Store appllication.

### ISSUE THREAD

**Issue by crionis1337** [Disassembler0/Win10-Initial-Setup-Script#265]
Hi there, I used your script and i accidentally deleted WindowsStore, next time i tried to use script with option to install WindowsStore it did nothing.
Any help would be appreciated.

**Comment by Disassembler0** [comment]
I've just tried on VM, to be sure, and it works, provided you didn't forget to include admin elevation and haven't used any other tweaking tools (some of which remove the AppX package completely).

Open regular command line (*cmd*), navigate to the directory with the script and run
```
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0Win10.ps1" -include "%~dp0Win10.psm1" RequireAdmin InstallWindowsStore
```

If that doesn't work, get an elevated PowerShell (run as admin), run the following and paste all the output here.

```
Get-AppxPackage -AllUsers "Microsoft.DesktopAppInstaller" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
Get-AppxPackage -AllUsers "Microsoft.Services.Store.Engagement" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
Get-AppxPackage -AllUsers "Microsoft.StorePurchaseApp" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
Get-AppxPackage -AllUsers "Microsoft.WindowsStore" | ForEach-Object {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
```

**Comment by crionis1337** [comment]
hello there, thank you for the fast response.

First i tried to do it with the cmd and i got this message: The argument
'%~dp0Win10.ps1' to the -File parameter does not exist. Provide the path to
an existing '.ps1' file as an argument to the -File parameter.

when i tried to do the second thing in PowerShell as an admin it did
nothing.

once again, thank you very much for helping me.

**Comment by crionis1337** [comment]
To be honest i just run the script when i downloaded it and later on i
figured out some things should be excluded.

**Comment by crionis1337** [comment]
I have deleted ~dp0 from the Win10 lines and managed to get to powershell message which says installing windows store but i still can't find it.

**Comment by Disassembler0** [comment]
The tweak for Windows Store removal is excluded by default, so if you haven't manually uncommented `UninstallWindowsStore` in *Default.preset*, then it wasn't this script what uninstalled Windows Store.

1) When you say "*it did nothing*", did it at least briefly show the progress bar on the top of the powershell window? Like this
![store](https://user-images.githubusercontent.com/5568046/65167213-66dd8100-da42-11e9-97d7-b29601dd56be.png)

2) Try opening *Run* prompt (either via right-clicking on Start Menu or via Win+R keyboard shortcut) and run
    ```
    ms-windows-store:
    ```
    It should either launch the Store or give you an error message "You'll need a new app to open this ms-windows-store link". Let me know what was the result.

3) Please run following command from elevated PowerShell and pase the output
    ```
    Get-AppxPackage -AllUsers "Microsoft.WindowsStore"
    ```

**Comment by crionis1337** [comment]
Ok, so i saw those commands on internet and used them, once it showed that
progress bar, while most of the times it did not.
2.windows cannot find ms-windows-store. Make sure you typed the name
correctly...
3. when i run that command it just moves to a new line to type in a command.

Strange i know :(

**Comment by crionis1337** [comment]
OS Name	Microsoft Windows 10 Enterprise LTSC
Version	10.0.17763 Build 17763
dont know if it might be useful.

**Comment by Disassembler0** [comment]
> 3. when i run that command it just moves to a new line to type in a command.

Yeah, so this tells us it definitely wasn't caused by the script. Even though there were several attempts (#130, #165, #239, #243) to add tweaks which would uninstall AppX packages for good, your case is the exact reason why I have never added them so far. Because such modifications can't be easily reverted.

There is a rough outline what to do in case something like this happens in my script here:
https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/91a6afba1fd78e07c54a89518f31c633598568c0/Win10.psm1#L2999-L3004
However it requires an installation media and some skills and insight into what you're about to do, because the comments are really just a general guidance.

There's also answered question about the same on [superuser.com](https://superuser.com/questions/949112/restore-microsoft-store-application-in-windows-10), but this solution also requires another source of files (another PC or a virtual machine) you need to copy.

**Comment by crionis1337** [comment]
Thanks very much for the answer! 
I feared it would come to this, I'll see what i can do with this WindowsApps, etc. and hopefully will bring to a working condition again :)

**Comment by crionis1337** [comment]
I'm exactly missing Windows Store app in my WindowApps folder.

**Comment by crionis1337** [comment]
I managed to get the Windows Store app back with a help of superuser.com and most importantly your help!

Thanks a million!

**Comment by CHEF-KOCH** [comment]
[Microsoft officially does not recommend removing the Store application](https://support.microsoft.com/en-us/help/4339074/removing-uninstalling-reinstalling-microsoft-store-app-not-supported). 

> In Windows 10, we do not recommend removing or uninstalling the Microsoft Store app.

> If you uninstalled Microsoft Store by any means and want to reinstall it, the only Microsoft-supported method is to reset or reinstall the operating system, which will reinstall Microsoft Store.


Instead, people should use:
* GPO's
* The official MS Store management tool (works with Home/Pro editions too)
* Set the MS Store to "private" (zero connections)
* AppLocker
