### ISSUE TITLE
Is there a way to undo entire thing

### ISSUE THREAD

**Issue by Rapidfalcon101** [Disassembler0/Win10-Initial-Setup-Script#267]
My friend put this on my computer and said it was cool, i dont like it. any way to undo the entire thing?

**Comment by Clownfused** [comment]
This link has info that may help you: https://github.com/Disassembler0/Win10-Initial-Setup-Script/issues/230#issuecomment-487318109

**Comment by c-rilaun** [comment]
Hi @Rapidfalcon101 ;

Does the link given by @Clownfused helped you ?
Feel free to reach back to us !

Just don't forget to say hello, please & thanks, like when you go buy bread or grocery.
