### ISSUE TITLE
someone knows how to rollback the taskbar icons?

### ISSUE THREAD

**Issue by beranos** [Disassembler0/Win10-Initial-Setup-Script#268]
hi, does someone know how i can rollback the taskbar icons? i don't like them being flatted out.
also saw this issues but the OP closed it so no one could reply to it, here's the link: https://github.com/Disassembler0/Win10-Initial-Setup-Script/issues/181

**Comment by Disassembler0** [comment]
Icon size is set by `ShowSmallTaskbarIcons` / `ShowLargeTaskbarIcons` tweaks.

Combining is set by `SetTaskbarCombineWhenFull` / `SetTaskbarCombineNever` / `SetTaskbarCombineAlways`.

To rollback the taskbar icon settings and make them look like on a freshly installed system, run `ShowLargeTaskbarIcons` and `SetTaskbarCombineAlways`.

**Comment by beranos** [comment]
i tried running those with 
powershell.exe -NoProfile -ExecutionPolicy Bypass -File Win10.ps1 -include Win10.psm1 RequireAdmin SetTaskbarCombineAlways
and 
powershell.exe -NoProfile -ExecutionPolicy Bypass -File Win10.ps1 -include Win10.psm1 RequireAdmin ShowLargeTaskbarIcons 

but the taskbar icons are still flatted out

**Comment by Disassembler0** [comment]
Did you log out and log back in afterwards, so the changes are taken into effect? If so, then I probably don't understand what you mean by "*flatted out*". A screenshot might help.

Nevertheless, these tweaks are done on per-user basis, so you can simply change whatever you like via right clicking the taskbar and going to *Taskbar settings*. The tweaks do the same as manually modifying *Use small taskbar buttons* and *Combine taksbar buttons* options.

**Comment by beranos** [comment]
logging out and logging back fixed it! thank you
