### ISSUE TITLE
DisableTelemetry causes 2 minute login delay/DCOM error

### ISSUE THREAD

**Issue by RTTrickster** [Disassembler0/Win10-Initial-Setup-Script#270]
As per subject - in testing when I baked the script into a fresh-build process this particular function caused a 1-2 minute login delay and DCOM failure errors in Windows event log. 

Tested in 1809, 1903 via Intune deployment. 

Event details;
Source - DistributedCOM
ID - 10010
Log - System
https://ibb.co/KLDk7hG for screenshot

If I run EnableTelemetry, the error and login delay goes away.

**Comment by Disassembler0** [comment]
> ...via Intune deployment

I'd say "Works as designed" :) You can't disable snitching functions and expect cloud-based deployment/enrollment process which relies on them to work.

> If I run EnableTelemetry, the error and login delay goes away.

If you run DisableTelemetry again afterwards, is the delay back or is it sufficient when the enrollment passes just once?

Are you willing to experiment to find out which registry keys set by DisableTelemetry are causing this? I don't have access to Intune to try myself.

**Comment by RTTrickster** [comment]
Yea I agree, if you want certain things to work, then certain features need to remain enabled :) 

Strangely the delay did not seem to reappear again if you DisableTelemetry again. 

I'll see if I can fire up some VM's again for testing, have had to move on to another project for the moment though. Thanks for your time, and for this awesome script.
