### ISSUE TITLE
DisableWAPPush breaks communications between device and Intune

### ISSUE THREAD

**Issue by RTTrickster** [Disassembler0/Win10-Initial-Setup-Script#271]
This is not so much a script issue as an FYI for anyone in this boat - this service is required for your client machine to talk to Intune for status updates, etc. 

Tested in 1809, 1903. 

Running EnableWAPPush restores comm's between device and service.

**Comment by Cubox-** [comment]
Lost many days of my life due to this. After reinstalling Windows, I figured the issue happened after running the script. Checking the issue gave me this.

Thanks for the issue, I can finally sleep well knowing I found where the issue came from.
