### ISSUE TITLE
BUG: Defender staying running

### ISSUE THREAD

**Issue by LukasKysela** [Disassembler0/Win10-Initial-Setup-Script#273]
Defender staying running.
After use "DisableDefender" then running Defender in Task Manager (and using CPU).

SmartScreen runing too.

Tested on Windows 10 1909

**Comment by Disassembler0** [comment]
`DisableDefender`, `DisableSmartScreen` and bunch of other tweaks need reboot to be fully taken into effect. Generally, it's a good idea to reboot after any reconfiguration in services or HKLM hive. Would it be helpful to add this into FAQ?

**Comment by LukasKysela** [comment]
Yes, I did. I tried O and O ShutUp software and it Defender and Smartscreen completely disabled after restart.

**Comment by Disassembler0** [comment]
I've tried it yesterday based on your report and had no problems disabling both. Paste or attach your preset, might be related to #272
