### ISSUE TITLE
User/Admin  Versions

### ISSUE THREAD

**Issue by MM-CMS** [Disassembler0/Win10-Initial-Setup-Script#28]
Would it be possible to insert a check for "if the user is admin"?

This way "tweaks" to the system as a whole are run as admin, 
otherwise user level UI changes can be pushed via GP or other methods and will not prompt for elevation.

This way this awesome script could be used for both admin system setups and ensuring that users have unified experience in their own profiles.

**Comment by Disassembler0** [comment]
This is exactly what was covered in issue #11 and what the 2.8 release introduced in commit 727bf0d09b4985c2a436a3b1e92ddf9aba410931.

You just need to write your own preset with the tweaks you'd like to apply. As long as the preset does not contain `RequireAdmin`, no admin rights are necessary and no auto-elevation will happen. Or am I misunderstanding your request?
