### ISSUE TITLE
How restore factory default ?

### ISSUE THREAD

**Issue by AnubisMann** [Disassembler0/Win10-Initial-Setup-Script#280]
Hi
How can I restore all original Windows values to default?

**Comment by Disassembler0** [comment]
Create a custom preset using tweaks listed in 2nd column of https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/master/Default.preset. See https://github.com/Disassembler0/Win10-Initial-Setup-Script/issues/230#issuecomment-487318109 for some more explanation.
Also, closing as duplicate of #267 and #230
