### ISSUE TITLE
Notification center disabled / 

### ISSUE THREAD

**Issue by IamCampos** [Disassembler0/Win10-Initial-Setup-Script#282]
Anyone knows a way to let the Notification Center appers again after using this script?
thanx

**Comment by Disassembler0** [comment]
Run `EnableActionCenter` tweak.

**Comment by IamCampos** [comment]
i did it, but doesn't appear again, as doesnt appear anymore the group of icons in the low right corner of the screen. I don't know if it's clear, but surely it has a particular name.

**Comment by Disassembler0** [comment]
You might need to run that tweak as admin, as it unsets a GPO. Also, did you restart (or at least log off / log on) afterwards?

The area left from the clock is usually called _SysTray_, the icon right from the clock is the notification center. `EnableActionCenter` handles the right part.

If you're still stuck, paste a screenshot. Just the bottom right part of your screen, where the icons should be, is enough.

**Comment by IamCampos** [comment]
This is how it is now:
![1](https://user-images.githubusercontent.com/58555754/70241807-f6581d80-176f-11ea-9be4-281d8b2021a6.jpg)

This is how i'd like it to be:
![2](https://user-images.githubusercontent.com/58555754/70241834-066ffd00-1770-11ea-8677-578c7d98217f.png)

**Comment by Disassembler0** [comment]
So yeah, run a preset
```
RequireAdmin
EnableActionCenter
HideTrayIcons
Restart
```
