### ISSUE TITLE
ShowBuildNumberOnDesktop doesn't update build number after update/upgrade.

### ISSUE THREAD

**Issue by lithium720** [Disassembler0/Win10-Initial-Setup-Script#283]
I tried disabling and re-enabling the option to no avail, is this build information being cached or pulled from a static registry key or something?

![Image](https://lithi.io/file/RB3S.png)

**Comment by Disassembler0** [comment]
It's taken from `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion`, value `BuildLab`. And yes, even on clean installation of 1909 it still reads `18362.19h1_release.190318-1202`. Feel free to report it to Microsoft via Feedback Hub. They don't care anyway. :)
