### ISSUE TITLE
UnpinStartMenuTiles not working in Windows 10 1909

### ISSUE THREAD

**Issue by KurtTheBerner** [Disassembler0/Win10-Initial-Setup-Script#286]
The function UnpinStartMenuTiles does not work in Windows 10 1909, after executing it, the Start Menu remains unchanged.

**Comment by Disassembler0** [comment]
Can't reproduce on freshly installed 1909 Pro (18363.535).

Did you restart or at lease log off / log on after application of the tweak?

Could you please try to reapply the tweak once more? There can be some rare race condition when Windows are refreshing the collection after some trigger (like application installation), which can cause the original collection to be written even though you've previously emptied it.

**Comment by KurtTheBerner** [comment]
I did restart.
Now I tested it again and it worked correctly (after a restart)!
OS: 1909 Pro 18363.418

**Comment by Disassembler0** [comment]
Good to hear. The unpinning tweaks are still kinda hackish and experimental (more details in #8), so I'll chalk this one as accidental and close the ticket.
