### ISSUE TITLE
Lenovo Thinkpad 420 Video Issues

### ISSUE THREAD

**Issue by driscollw** [Disassembler0/Win10-Initial-Setup-Script#293]
I have a Thinkpad T420 that works fine until I run the script. Afterwards I cannot for the life of me get the video card driver to load, I get the device yellow warning in device manager. I disabled every option in the script and turned them on one at a time. Everything was good up until function UninstallThirdPartyBloat {. 

I think these packages seem to be important....not 100% sure. 
Get-AppxPackage "E046963F.LenovoCompanion" | Remove-AppxPackage
Get-AppxPackage "LenovoCorporation.LenovoID" | Remove-AppxPackage
Get-AppxPackage "LenovoCorporation.LenovoSettings" | Remove-AppxPackage

What was really odd is that even when I try to force the video driver to install, it will, I just won't load and gives a driver error.

**Comment by Disassembler0** [comment]
@agsimmons, Any idea here? Lenovo bloatware removal in #89 was your addition. Arguably a lot of things may have changed in the 20 months. For the moment, I'll just revert the commit.
