### ISSUE TITLE
Consider adding "DisableDefragmentation" setting

### ISSUE THREAD

**Issue by darkstar** [Disassembler0/Win10-Initial-Setup-Script#3]
Especially in virtual environments (with SAN based storage) it is important to disable the scheduled defragmentation. This is done by disabling the corresponding scheduled task, which can only be done from a SYSTEM account, not from a regular Admin account.

Usually what you'd have to do is something like (note the ``-s`` for psexec which means "run as SYSTEM")
``
psexec \\10.93.10.2 -u Administrator -p "p4ssw0rd" -s schtasks /change /tn "\Microsoft\Windows\TaskScheduler\Maintenance Configurator" /DISABLE
``

**Comment by darkstar** [comment]
Ah I just realized that this particular setting is the Win8.1/Win2012 setting, not the Win10 setting..

For Windows 10 the setting is hidden behind the "Optimize" button in the properties of any disk drive. I don't know (yet) which task or registry setting is behind this all

**Comment by Disassembler0** [comment]
"Optimize" button on Win10 maps to "\Microsoft\Windows\Defrag\ScheduledDefrag" task, therefore
```
Disable-ScheduledTask -TaskName "\Microsoft\Windows\Defrag\ScheduledDefrag"
```
seems to do the trick. I'll check if it works the same on Server 2016 and add it to the next version. Although I won't put it to default preset as your use case is a bit uncommon and Win10 are generally smart enough not to defragment SSD.
