### ISSUE TITLE
RequireAdmin

### ISSUE THREAD

**Issue by telvedin** [Disassembler0/Win10-Initial-Setup-Script#30]
The script Win10-Initial-Setup is awesome and run like charm I also add one function for removing  smile face on IE and working perfect. The question i have is: 
I want to use script on multiple workstation the problem I am running into is "RequireAdmin" prompt. The users I want run script don't have admin rights on the machine. Is it any way to add function with admin credentials to script and run as startup script silently without prompting users for admin credentials?

Thanks a lot

**Comment by Disassembler0** [comment]
Definitely not possible to add the credentials *into* the script, but you can use a wrapper for the script which allows you to store the credentials *externally* and automatically pass them during execution. See eg. tools like [RunAsSPC](http://robotronic.de/runasspc/), [RunItAs](https://runitas.en.softonic.com/), [Steel RunAs](http://www.steelsonic.com/steelrunas.htm) etc.

Alternatively, check the long-ass answer in #29, you might find a more suitable way of using the scrip there.
