### ISSUE TITLE
Skript patrně zruší funkčnost čteček karet (občanský průkaz, apod.)

### ISSUE THREAD

**Issue by Xavibo** [Disassembler0/Win10-Initial-Setup-Script#304]
Skript je super, akorát po jeho aplikaci na různých počítačích je na nich nefunkční čtečka karet. Jak integrovaná (např. v HP Zbook), tak i externí (např. Omnikey 3021). Na počítači kde je nainstalován skript nejde nainstalovat ani aplikace eObčanka, instalace končí nic neříkající hláškou "Systém nemůže otevřít zadaný soubor nebo zařízení". Nevím jak přijít na to, která volba ve skriptu toto blokuje ...

**Comment by Disassembler0** [comment]
Pár tweaků, které by mohly PC/SC ovlivňovat tam je, ale většina není ve výchozím presetu použitá. Bohužel momentálně nemám žádnou takovou čtečku po ruce, takže si to nemohu vyzkoušet na fyzickém hardware. S virtuální čtečkou mi instalace projde i pokud aplikují úplně všechny tweaky, které ve skriptu mám. Diagnostika eObčanky mi samozřejmě řekne, že ve čtečce není vložena žádná občanka, což je očekávatelné, nicméně čtečku samotnou vidí. Pokud je to skutečně vina některého z tweaků, pak bych jej hledal metodou půlení intervalů, tj. aplikovat polovinu tweaků - zjistit, zda se chyba projevila, pokud ano, polovinu revertovat, pokud ne, aplikovat polovinu ze zbývající poloviny a tak pořád dokola, dokud tweak neodhalím. Na to je samozřejmě vhodné pracovat ve virtuálce.

Pár upřesňujících dotazů:

1) Používáte výchozí _Default.preset_ nebo máte vlastní sadu tweaků? Pokud vlastní, prosím o přiložení.

2) V případě, že skript vůbec neaplikujete, běží čtečka i eObčanka podle očekávání?

3) Ta hláška se objeví přesně v které fázi? Na konci instalace eObčanka, kterou instalujete z https://info.eidentita.cz/Download/ souborem eObcanka_x64.exe? Před nebo po vytvoření zástupců? Co se pak děje s instalací? eObčanka se zase odinstaluje nebo zůstane nainstalovaná?

4) Je čtečka karet vidět ve správci zařízení, včetně správného názvu a korektně nainstalovaných ovladačů?

5) Je některá z těchto služeb spuštěna? Obě by měly mít nastaveno ruční spouštění aktivační událostí a pokud je připojena čtečka, první služba by měla běžet.
    - Čipová karta
    - Služba výčtu zařízení čipové karty

**Comment by Xavibo** [comment]
1. myslím si, že default, ale pro jistotu ho přikládám.
[Preset.zip](https://github.com/Disassembler0/Win10-Initial-Setup-Script/files/4450680/Preset.zip)

2. ano

3. 64bit verze => spustit => Další => Souhlasím s podmínkami, Další => Instalovat => prakticky se ta instalace ani nerozběhne a skončí hláškou viz Inst1.png => odklepnu a dostanu Inst2.png
![Inst1](https://user-images.githubusercontent.com/63339817/78788625-5b38b400-79ac-11ea-9d12-e6f7e99f4cd8.png)
![Inst2](https://user-images.githubusercontent.com/63339817/78788630-5d027780-79ac-11ea-809e-1d272b5f7ed3.png)

4. ano, je tam vidět, bez chyb
![Ctecka](https://user-images.githubusercontent.com/63339817/78788767-87543500-79ac-11ea-86b6-0de670de3814.png)

5. první spuštěna je, druhá ne

![Sluzby](https://user-images.githubusercontent.com/63339817/78789044-e619ae80-79ac-11ea-8c1e-83e886832937.png)

**Comment by Disassembler0** [comment]
Ten preset je skoro rok starý, z verze skriptu 3.7. Pokud je stejně starý i samotný skript s knihovnou tweaků, může tam docházet ke nějaké chybě, která už byla dávno opravena při jiné příležitosti. Nicméně použité tweaky vypadají vcelku bezpečně a nekonfliktně, takže nemyslím, že problém bude tam.

Nicméně ta chyba MSI installeru je zajímavá. 110 znamená, že se nepodařilo čtení z instalační databáze. K tomu může dojít třeba pokud na tom souboru drží zámek jiný proces, například antivir.

Co je ještě zajímavější je ta cesta. `F:\Temp\` rozhodně není výchozí umístění dočasných souborů, a to ani kdyby F:\ byla systémová jednotka. Jak toto umístění nastavujete? Změnou proměnné prostředí %TEMP%? Není to náhodou RAMdisk? Protože s těmi má MSI installer známé problémy.

**Comment by Xavibo** [comment]
Tak je to tak, veliká omluva.
Přes půl roku žiju v přesvědčení, že mi čtečky nefungují kvůli tomu skriptu.

Ano, ten TEMP je nalinkovaný na RAMdisk. Přelinkoval jsem to zpět na C: a … instalace prošla. A občanka funguje i když je pak TEMP zpět na F:. Asi mě mátlo to, že na Windows 7 instalace s TEMP na disku F: normálně fungovala, na Windows 10 s TEMP na disku F: instalace nefunguje. Loni v létě jsem koupil notebook s Windows 10, hned po vybalení mi tam čtečka karet fungovala, pak jsem aplikoval zdejší skript a asi mezi tím nahodil i ten TEMP na F: a po vzoru funkčních Windows 7 jsem si spojoval nefunkčnost čteček s aplikací skriptu …

Takže ještě jednou, má omluva.
Vše se skriptem funguje, jak má.
