### ISSUE TITLE
Tweak brief explanation

### ISSUE THREAD

**Issue by FIN392** [Disassembler0/Win10-Initial-Setup-Script#305]
Great job @Disassembler0. I'm new in GitHub so I don't know if the information is somewhere. Most of the tweaks are self-explanatory but where I find deeper information about those more tricky ones?

**Comment by Disassembler0** [comment]
There's a plan to have some wiki with broader explanation (#225), however the script is intended mainly for sysadmins and power users who already have an idea about what's going on. For the rest, I can currently suggest only reading the comments in the code for respective tweaks or searching the internet for the respective registry keys as they are usually documented in some technotes, documentations related to group policy or at least mentioned with some context on 3rd party forums.

**Comment by FIN392** [comment]
Thanks @Disassembler0. You are right, for those I don't know it takes my 2 minutes to get the info from web. A wiki is good idea; I also saw the web page of the french guy and it could be a good starting point.
