### ISSUE TITLE
Scripts hangs if SysInternals' Process Exlorer is the default task manager

### ISSUE THREAD

**Issue by x86dev** [Disassembler0/Win10-Initial-Setup-Script#31]
The scripts hangs if SysInternals' Process Exlorer is the default task manager -- this can be done by replacing the Windows Task Manager with the one from SysInternals.

To make the script work, the Windows Task Manager needs to be set being the default task manager first.

**Comment by Disassembler0** [comment]
As mentioned in [README](https://github.com/Disassembler0/Win10-Initial-Setup-Script#revert-functions)

> The default is considered freshly installed Windows 10 or Windows Server 2016 with no adjustments made during or after the installation.

As far as I know, there is no version or language mutation distributed with SysInternals tools by default, so if you have your installation already customized, then you have to customize also your preset. In this case exclude `ShowTaskManagerDetails` as it doesn't even make sense to use the tweak if you're using different tool anyway.
