### ISSUE TITLE
DisableUpdateDriver - using deprecated GPOs?

### ISSUE THREAD

**Issue by Bangaio65** [Disassembler0/Win10-Initial-Setup-Script#310]
The following GPOs don't apply to Windows 10 according to template description:
`Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DriverSearching" -Name "DontPromptForWindowsUpdate" -Type DWord -Value 1`
https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.DeviceSoftwareSetup::DriverSearchPlaces_DontPromptForWindowsUpdate_2

`Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DriverSearching" -Name "DontSearchWindowsUpdate" -Type DWord -Value 1`
https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.InternetCommunicationManagement::DriverSearchPlaces_DontSearchWindowsUpdate

> Supported on: Windows Server 2008, Windows Server 2003, Windows Vista, and Windows XP SP2

This one seems to be current:
System\Device Installation\Specify search order for device driver source locations: Do not search Windows Update
`reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\DriverSearching" /v SearchOrderConfig /t REG_DWORD /d 0 /f`
https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.DeviceSoftwareSetup::DriverSearchPlaces_SearchOrderConfiguration

Then there's also 
`reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\DriverSearching" /v SearchOrderConfig /t REG_DWORD /d 0 /f`
Source: https://www.wagnardsoft.com/forums/viewtopic.php?f=5&t=674
(probably does the same thing as the policy)

And what does `DriverUpdateWizardWuSearchEnabled` key do?. According to this topic, setting it to 0 (default is 1) causes:
https://www.tenforums.com/drivers-hardware/133482-device-manager-update-driver-issue.html

> So when I open Device Manager and say for example, I expand Network Adapters. Then if I right-click my Ethernet Adapter and select Update Driver and then Search automatically for updated driver software, it immediately says The best drivers for your device are already installed. This is the case for every single thing listed in device manager.

So maybe it shouldn't be disabled since it's a user-initiated process. (but I guess it won't work anyway if those other registry keys are set)

I don't have the time or energy to test all the different combinations of these settings, but I thought I'd put this out here. Thanks.

**Comment by Disassembler0** [comment]
Hmm... these were introduced in 03e501b48159c5e7a8712ae0746b656579c98334 2 years ago. Looking at the commit, I think I was frustrated by the behavior when I tried to use drivers not intended for a piece of hardware (but working regardless) and Windows were still trying to force their own drivers from WU. So I just slapped there all driver update related GPOs and didn't verify if they are even applicable for Win10. Strangely enough the `SearchOrderConfig` wasn't among them.

So yeah, what you're suggesting makes sense. I'll trim it a bit.
