### ISSUE TITLE
Add a Restore preset

### ISSUE THREAD

**Issue by maximousblk** [Disassembler0/Win10-Initial-Setup-Script#312]
Add a preset that resets everything to default. This can be handy if someone (me) messes up.

This can also be helpfull with the "Some setting are controlled by your organisation" problem.

I know you can do this by editing default preset but it would be nicer for noobs.

**Comment by cjerrington** [comment]
Restore points are only available on Windows 10 not Server OS. Another option might be needed for Server OS's.

**Comment by maximousblk** [comment]
For those who need it, I created a preset which reverts everything the *default preset* changes.

https://gist.github.com/maximousblk/2b43c0de7d6125787ec688eeab5a4e77

**Comment by ameeno** [comment]
+1

it would be nice to know what exactly changed when we did it, IE what is the default setting?

are we enabling something that was not enabled before?
