### ISSUE TITLE
Error on unpin 

### ISSUE THREAD

**Issue by ActiveByte** [Disassembler0/Win10-Initial-Setup-Script#316]
Can't find a fix for this problem.
But with everything i tried i keep geting this error.

The error: (wrapping it in code tags gave problems)
https://imgur.com/a/lKqPIup

**Comment by farag2** [comment]
Microsoft has blocked access to the pin/unpin function.

**Comment by Disassembler0** [comment]
@ActiveByte: You seem to have some ancient or experimental version of the script. This method has been reworked in January 2018 and last updated in October 2018. Please download the current version of the script, adjust your preset, if you have any customized one, and try again.

@farag2: They have blocked it long time ago, but the script circumvents it by editing the registry blob directly. So far it works with pretty high success rate.

**Comment by farag2** [comment]
@Disassembler0, I thought he was trying to pin something to the Start menu.

**Comment by Disassembler0** [comment]
@farag2: He was, but that's not what I have in the script, so I wonder there did he get it... and if it's even my script. :)

**Comment by farag2** [comment]
I had to completely switch to the syspin app to automate pinning shortcuts in my script. Could not think of anything to solve this problem. :( One decompiled that app. May be one day it would be pissible to convert it into PS script. https://github.com/airwolf2026/Win10Pin2TB
