### ISSUE TITLE
Can I use this script for the new Windows 10 Fall Creators Update?

### ISSUE THREAD

**Issue by onmyouji** [Disassembler0/Win10-Initial-Setup-Script#32]
Hello,

Can I use this script for the new Windows 10 Fall Creators Update?

**Comment by Kaspej** [comment]
I have used it with no problems on fresh install.

**Comment by onmyouji** [comment]
@Kaspej 
Ok, thanks

**Comment by Disassembler0** [comment]
Since the update came out yesterday, I haven't had the chance to test it. I'm planning to do so next week.

Generally the script should be safe to run. It worst case, few tweaks won't be applied as they're supposed to, but it shouldn't break anything.

**Comment by Disassembler0** [comment]
I've checked today on fresh 1709 (RS3) aka Fall Creators Update. The script works without any modifications, so I've just added a comment about implicitly disabled SMBv1 and that's pretty much everything what was needed for the new build.
