### ISSUE TITLE
Cortana is back in 2004 Start Menu

### ISSUE THREAD

**Issue by Disassembler0** [Disassembler0/Win10-Initial-Setup-Script#321]
Also this is off-topic but Cortana is back in my Start Menu too. I followed the instructions in <https://winaero.com/blog/uninstall-and-remove-cortana-in-windows-10-version-2004/> and got rid of it.

_Originally posted by @a-vrma in https://github.com/Disassembler0/Win10-Initial-Setup-Script/issues/320#issuecomment-643723825_

**Comment by farag2** [comment]
Also how to disable autostarting it

```
if (Get-AppxPackage -AllUsers -Name Microsoft.549981C3F5F10)
{
	New-ItemProperty -Path "Registry::HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\Microsoft.549981C3F5F10_8wekyb3d8bbwe\CortanaStartupId" -Name State -PropertyType DWord -Value 1 -Force
}
```
