### ISSUE TITLE
20H1: Bing web search in task bar need new registry setting

### ISSUE THREAD

**Issue by JustMyGithub** [Disassembler0/Win10-Initial-Setup-Script#323]
Computer\HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows\Explorer

DWORD DisableSearchBoxSuggestions = 1

found on https://www.howtogeek.com/224159/how-to-disable-bing-in-the-windows-10-start-menu/

**Comment by Disassembler0** [comment]
Duplicate of #300. It's not that straightforward, unfortunately.
