### ISSUE TITLE
get rid of DisableLockScreenRS1 

### ISSUE THREAD

**Issue by JustMyGithub** [Disassembler0/Win10-Initial-Setup-Script#326]
I think it is not useful to have a version-specific setting. Why not integrate it like "if Version between 1607 and 1709 use DisableLockScreenRS1 else ..."

**Comment by Disassembler0** [comment]
`DisableLockScreenRS1` should have never existed in the first place. It uses completely hacky way of doing *something* what happens to have similar result as `DisableLockScreen`, but it's incompatible with it. It was just a workaround for a bug brought in by Microsoft at the time. The tweaks survives mostly as a historical reference, possibly to be used by people using LTSB (or simply outdated) versions. Similar to `EnableMeltdownCompatFlag` and some other one-off tweaks with no real use on current versions.
