### ISSUE TITLE
Safely Remove Hardware and Eject Media icon

### ISSUE THREAD

**Issue by Qrzysio** [Disassembler0/Win10-Initial-Setup-Script#34]
Is it possible  to remove `Safely Remove Hardware and Eject Media` icon? Would be so nice to see it as the new feature of your script.

**Comment by Disassembler0** [comment]
Unfortunately not possible using a clean way.

There is a registry key under `HKCU\Software\Microsoft\Windows\CurrentVersion\Applets\SysTray` called `Services` which can be set to decimal value `29` to temporarily hide the icon, but it only persists until next logon.

In case you see disks there, check if your BIOS/UEFI has the option to enable/disable hotswap on them. If it doesn't, you can force it using registry keys described in answers for [this StackOverflow question](https://superuser.com/questions/12955/how-can-i-remove-the-option-to-eject-sata-drives-from-the-windows-7-tray-icon). For other devices you can again check BIOS/UEFI or driver options in *Device Manager*. All of these fixes are way too specific to be added to the script.
