### ISSUE TITLE
EnableActionCenter not work after DisableActionCenter

### ISSUE THREAD

**Issue by QingKongBaiYu** [Disassembler0/Win10-Initial-Setup-Script#341]
win10 ver: 19041.450.

**Comment by E3V3A** [comment]
What do you mean not working?
Screenshot?

**Comment by QingKongBaiYu** [comment]
I reinstalled win10 and then worked.

**Comment by E3V3A** [comment]
@QingKongBaiYu 
So if it is working then please close the issue.
