### ISSUE TITLE
Windows 10 - 1709 - Nabídka start - Zobrazování návrhů

### ISSUE THREAD

**Issue by Dvorak-Stepan** [Disassembler0/Win10-Initial-Setup-Script#35]
Došlo ke změně v registru:
[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager]
"SubscribedContent-338388Enabled"=dword:00000000

**Comment by Dvorak-Stepan** [comment]
Ještě jsem našel možnost, jak zakázat další doporučení, typy a hry, které se časem sami doinstalovaly:
https://www.tenforums.com/general-support/93066-my-last-day-windows-10-a-2.html

**Comment by Disassembler0** [comment]
Hm. To by měl řešit tweak `DisableConsumerApps` na úrovni GPO, ale je možné, že to v 1709 taky "opravili".   Jak budu mít chvíli, tak na to kouknu. Dík za podnět.
