### ISSUE TITLE
HideFromThisPC also hides from Userprofile

### ISSUE THREAD

**Issue by Janzzze** [Disassembler0/Win10-Initial-Setup-Script#36]
HideDocumentsFromThisPC and similar also hides the folder from Userprofile.

Method used before change to using ThisPcPolicy does not have this potentially unwanted behavior.

**Comment by Disassembler0** [comment]
That method sometimes didn't have even the wanted behavior, that's why it was changed in the first place. Is this behavior new in 1709 or has it always been there?

**Comment by Janzzze** [comment]
I have only tested with 1709 so don't know if existed before that.
