### ISSUE TITLE
App tiles disappeared

### ISSUE THREAD

**Issue by Qrzysio** [Disassembler0/Win10-Initial-Setup-Script#40]
I recently tested your script on a two machines with Win 10 Pro and Home versions (the latest).

In both cases app tiles from star menu disappeared after the reboot. It looks like this:
![001](https://user-images.githubusercontent.com/13356480/32651802-2392c1aa-c63d-11e7-8ce7-d3d4c5a314c8.jpg)
![002](https://user-images.githubusercontent.com/13356480/32651803-23c44de2-c63d-11e7-9e3e-90cd4ede6865.jpg)

When I click on any tile with the arrow `You will need a new app to open this ms-get-started` dialog appears. It's actually not a big deal, because most of the tiles are games etc. but to get rid of it I have to unpin everything from star menu and then pin again.

at first I thought it was not caused by script and tried to find any solution. [Microsoft answer](https://answers.microsoft.com/en-us/windows/forum/windows_10-start-winpc/app-tiles-disappeared-from-windows-10-start-menu/5d8abf5b-f73b-45f1-9d80-b988cd6da49a) does not help at all though.

I attach config I have used (on both machines) so maybe you will solve the problem out.

	### Privacy Settings ###
	"DisableTelemetry",             # "EnableTelemetry",
	"DisableWiFiSense",             # "EnableWiFiSense",
	"DisableSmartScreen",         # "EnableSmartScreen",
	"DisableWebSearch",             # "EnableWebSearch",
	"DisableStartSuggestions",      # "EnableStartSuggestions",
	"DisableLocationTracking",      # "EnableLocationTracking",
	"DisableMapUpdates",            # "EnableMapUpdates",
	"DisableFeedback",              # "EnableFeedback",
	"DisableAdvertisingID",         # "EnableAdvertisingID",
	"DisableCortana",               # "EnableCortana",
	"DisableErrorReporting",        # "EnableErrorReporting",
	"SetP2PUpdateLocal",            # "SetP2PUpdateInternet",
	"DisableAutoLogger",            # "EnableAutoLogger",
	"DisableDiagTrack",             # "EnableDiagTrack",
	"DisableWAPPush",               # "EnableWAPPush",

	### Service Tweaks ###
	"SetUACLow",                  # "SetUACHigh",
	# "EnableSharingMappedDrives",  # "DisableSharingMappedDrives",
	"DisableAdminShares",           # "EnableAdminShares",
	"DisableSMB1",                # "EnableSMB1",
	# "SetCurrentNetworkPrivate",     # "SetCurrentNetworkPublic",
	"SetUnknownNetworksPrivate",  # "SetUnknownNetworksPublic",
	"DisableCtrldFolderAccess",   # "EnableCtrldFolderAccess",
	"DisableFirewall",            # "EnableFirewall",
	"DisableDefender",            # "EnableDefender",
	"DisableUpdateMSRT",          # "EnableUpdateMSRT",
	# "DisableUpdateDriver",        # "EnableUpdateDriver",
	"DisableUpdateRestart",         # "EnableUpdateRestart",
	"DisableHomeGroups",            # "EnableHomeGroups",
	"DisableSharedExperiences",     # "EnableSharedExperiences",
	"DisableRemoteAssistance",      # "EnableRemoteAssistance",
	"DisableRemoteDesktop",       # "EnableRemoteDesktop",
	"DisableAutoplay",              # "EnableAutoplay",
	"DisableAutorun",               # "EnableAutorun",
	"DisableDefragmentation",     # "EnableDefragmentation",
	"DisableSuperfetch",          # "EnableSuperfetch",
	"DisableIndexing",            # "EnableIndexing",
	# "SetBIOSTimeUTC",             # "SetBIOSTimeLocal",
	"DisableHibernation",         # "EnableHibernation",
	"DisableFastStartup",         # "EnableFastStartup",

	### UI Tweaks ###
	"DisableActionCenter",          # "EnableActionCenter",
	# "DisableLockScreen",            # "EnableLockScreen",
	"DisableLockScreenRS1",       # "EnableLockScreenRS1",
	"HideNetworkFromLockScreen",    # "ShowNetworkOnLockScreen",
	# "HideShutdownFromLockScreen",   # "ShowShutdownOnLockScreen",
	"DisableStickyKeys",            # "EnableStickyKeys",
	"ShowTaskManagerDetails"        # "HideTaskManagerDetails",
	"ShowFileOperationsDetails",    # "HideFileOperationsDetails",
	"DisableFileDeleteConfirm",     # "EnableFileDeleteConfirm",
	"HideTaskbarSearchBox",         # "ShowTaskbarSearchBox",
	"HideTaskView",                 # "ShowTaskView",
	"ShowSmallTaskbarIcons",        # "ShowLargeTaskbarIcons",
	"ShowTaskbarTitles",            # "HideTaskbarTitles",
	"HideTaskbarPeopleIcon",        # "ShowTaskbarPeopleIcon",
	"HideTrayIcons",                # "ShowTrayIcons",
	"ShowKnownExtensions",          # "HideKnownExtensions",
	"HideHiddenFiles",              # "ShowHiddenFiles",
	"HideSyncNotifications"         # "ShowSyncNotifications",
	"HideRecentShortcuts",          # "ShowRecentShortcuts",
	"SetExplorerThisPC",            # "SetExplorerQuickAccess",
	"ShowThisPCOnDesktop",          # "HideThisPCFromDesktop",
	"HideDesktopFromThisPC",        # "ShowDesktopInThisPC",
	"HideDocumentsFromThisPC",      # "ShowDocumentsInThisPC",
	"HideDownloadsFromThisPC",      # "ShowDownloadsInThisPC",
	"HideMusicFromThisPC",          # "ShowMusicInThisPC",
	"HidePicturesFromThisPC",       # "ShowPicturesInThisPC",
	"HideVideosFromThisPC",         # "ShowVideosInThisPC",
	"Hide3DObjectsFromThisPC",      # "Show3DObjectsInThisPC",
	"SetVisualFXPerformance",       # "SetVisualFXAppearance",
	# "DisableThumbnails",          # "EnableThumbnails",
	"DisableThumbsDB",              # "EnableThumbsDB",
	# "AddENKeyboard",              # "RemoveENKeyboard",
	"EnableNumlock",              # "DisableNumlock",

	### Application Tweaks ###
	"DisableOneDrive",              # "EnableOneDrive",
	"UninstallOneDrive",            # "InstallOneDrive",
	"UninstallMsftBloat",           # "InstallMsftBloat",
	"UninstallThirdPartyBloat",     # "InstallThirdPartyBloat",
	# "UninstallWindowsStore",      # "InstallWindowsStore",
	"DisableConsumerApps",          # "EnableConsumerApps",
	"DisableXboxFeatures",          # "EnableXboxFeatures",
	"DisableAdobeFlash",            # "EnableAdobeFlash",
	# "UninstallMediaPlayer",       # "InstallMediaPlayer",
	"UninstallWorkFolders",       # "InstallWorkFolders",
	# "InstallLinuxSubsystem",      # "UninstallLinuxSubsystem",
	# "InstallHyperV",              # "UninstallHyperV",
	# "SetPhotoViewerAssociation",    # "UnsetPhotoViewerAssociation",
	# "AddPhotoViewerOpenWith",       # "RemovePhotoViewerOpenWith",
	"DisableSearchAppInStore",      # "EnableSearchAppInStore",
	"DisableNewAppPrompt",          # "EnableNewAppPrompt",
	"EnableF8BootMenu",             # "DisableF8BootMenu",
	"SetDEPOptOut",                 # "SetDEPOptIn",

	### Server Specific Tweaks ###
	# "HideServerManagerOnLogin",   # "ShowServerManagerOnLogin",
	# "DisableShutdownTracker",     # "EnableShutdownTracker",
	# "DisablePasswordPolicy",      # "EnablePasswordPolicy",
	# "DisableCtrlAltDelLogin",     # "EnableCtrlAltDelLogin",
	# "DisableIEEnhancedSecurity",  # "EnableIEEnhancedSecurity",

	### Auxiliary Functions ###
	"WaitForKey",
	"Restart"

Additionally I commented the line that deletes the MSN Weather app.

**Comment by Disassembler0** [comment]
But.. but that was your suggestion! :)

`DisableBackgroundApps` does that. Tiles are running and fetching their content as background apps. In hindsight, it was probably not a good idea to enable the tweak in default configuration.

**Comment by Qrzysio** [comment]
The description is short and I didn't get it causes this behaviour. Now it's clear. Thank you.
