### ISSUE TITLE
Disable automatic install printers

### ISSUE THREAD

**Issue by peekaa** [Disassembler0/Win10-Initial-Setup-Script#47]
Would it be posiible to add feature "Disable automatic install network printers"? Thank you.

**Comment by Disassembler0** [comment]
Just to be sure, we're talking about this - https://superuser.com/questions/290166/prevent-network-printers-automatically-being-added-to-devices-and-printers-in - right?

**Comment by peekaa** [comment]
Yes, I believe so.
