### ISSUE TITLE
locking windows to think it's managed by organisation

### ISSUE THREAD

**Issue by michondr** [Disassembler0/Win10-Initial-Setup-Script#49]
hey, this happens every time I use these scripts, something locks the settings.
![capture](https://user-images.githubusercontent.com/29277166/34360399-cb7e61a2-ea60-11e7-82b2-409ea4f454a3.PNG)
Do you know how to get around this?

**Comment by Disassembler0** [comment]
Most of the settings are set via local GPO. If you set GPO, Windows assume the setting is set by your organization, so you'll get this exact message for the settings set by the GPO.
