### ISSUE TITLE
Power Plan Tweaks

### ISSUE THREAD

**Issue by thecek** [Disassembler0/Win10-Initial-Setup-Script#50]
Greetings @Disassembler0 ,

I´ve come up with some tweaks for dealing with power plan settings that may be nice to include on your script, as na special session if you find interesting.

On laptops and batteries devices I think it really helps when you don´t have to remember all settings are.

In fact I use a laptop as server machine, and I don´t want it to turnoff anytime and wish everything online all the time.

Here is some piece of code that shows how to do it. Also tried to keep it clean with only powercfg snippet:

```
# Set Monitor presets to 'never' 

powercfg -change -monitor-timeout-ac 0
powercfg -change -monitor-timeout-dc 0
powercfg -change -standby-timeout-ac 0
powercfg -change -standby-timeout-dc 0
powercfg -change -disk-timeout-ac 0
powercfg -change -disk-timeout-dc 0
powercfg -change -hibernate-timeout-ac 0
powercfg -change -hibernate-timeout-dc 0

# 48e6b7a6-50f5-4782-a5d4-53bb8f07e226  (Configuração de suspensão seletiva USB)

# USB Suspensão Seletiva - Desabilitar
powercfg /SETACVALUEINDEX SCHEME_CURRENT 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 0
powercfg /SETDCVALUEINDEX SCHEME_CURRENT 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 0


# Hibernar - Desabilitar
powercfg -h off

# GUID de Subgrupos: 44f3beca-a7c0-460e-9df2-bb8b99e0cba6  (Intel(R) Graphics Settings)
#     GUID de Configuração de Energia: 3619c3f2-afb2-4afc-b0e9-e7fef372de36  (Intel(R) Graphics Power Plan)

powercfg /SETACVALUEINDEX SCHEME_CURRENT 44f3beca-a7c0-460e-9df2-bb8b99e0cba6 3619c3f2-afb2-4afc-b0e9-e7fef372de36 2

#   GUID de Subgrupos: 4f971e89-eebd-4455-a8de-9e59040e7347  (Botões de energia e tampa)
#     Alias GUID: SUB_BUTTONS
#     GUID de Configuração de Energia: 5ca83367-6e45-459f-a27b-476b1d01c936  (Ação de fechamento da tampa)
#       Alias GUID: LIDACTION

powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_BUTTONS LIDACTION 0
powercfg /SETDCVALUEINDEX SCHEME_CURRENT SUB_BUTTONS LIDACTION 0

#     GUID de Configuração de Energia: 7648efa3-dd9c-4e3e-b566-50f929386280  (Ação do botão para ligar/desligar)
#       Alias GUID: PBUTTONACTION

powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_BUTTONS PBUTTONACTION 0
powercfg /SETDCVALUEINDEX SCHEME_CURRENT SUB_BUTTONS PBUTTONACTION 0


#     GUID de Configuração de Energia: 96996bc0-ad50-47ec-923b-6f41874dd9eb  (Ação do botão de suspensão)
#       Alias GUID: SBUTTONACTION

powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_BUTTONS SBUTTONACTION 0
powercfg /SETDCVALUEINDEX SCHEME_CURRENT SUB_BUTTONS SBUTTONACTION 0


#     GUID de Configuração de Energia: a7066653-8d6c-40a8-910e-a1f54b84c7e5  (Botão para ligar/desligar do menu Iniciar)
#       Alias GUID: UIBUTTON_ACTION

powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_BUTTONS UIBUTTON_ACTION 2
powercfg /SETDCVALUEINDEX SCHEME_CURRENT SUB_BUTTONS UIBUTTON_ACTION 2


# Enable Sleep Option
Function EnableSleep {
	Write-Host "Enabling Sleep..."
	Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FlyoutMenuSettings" -Name "ShowSleepOption" -Type Dword -Value 1
}


# Disable Sleep Option
Function DisableSleep {
	Write-Host "Disabling Sleep..."
	Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FlyoutMenuSettings" -Name "ShowSleepOption" -Type Dword -Value 0
}


DisableSleep
```

Some comments are in portuguese, however you may rip them off.

Also the GUIDs are default for any language.

It does apply to current energy plan however it would be nice to create a new energy scheme (that I still don´t know how to do) to apply them in a separated way.

Regards,
@thecek

**Comment by Disassembler0** [comment]
I have already thought about adding some energy scheme tweaks but then refrained from it as different people expect their machines to behave differently and sometimes even drivers change energy schemes (typically various energy management tools like [this one](http://www.lenovoblog.cz/wp-content/uploads/2014/02/Vstiek5.png)). Since we have multiple possible actions for multiple controls in multiple profiles, it would be just way too confusing to create modular tweaks for all of them.

That being said, I will at least add the tweak to disable monitor+standby timeouts and also to disable the sleep option. The rest is pretty specific for your use case.

> it would be nice to create a new energy scheme (that I still don´t know how to do)

I'd start with 
```
powercfg /DUPLICATESCHEME SCHEME_CURRENT
powercfg /CHANGENAME <GUID> <newname>
powercfg /SETACTIVE <GUID>
...
```
Alternatively, you can set everything manually and then just `powercfg /EXPORT <filename> <GUID>` and on new installations `powercfg /IMPORT <filename>`. Still, I'm not planning to accept any PRs modifying the energy schemes, so feel free to do it for your own needs.
