### ISSUE TITLE
Windows Update disable/enable

### ISSUE THREAD

**Issue by huglester** [Disassembler0/Win10-Initial-Setup-Script#56]
Hello,
If I understand correct, this powershell script does not offer enablind/disabling windows updates?

Thank you

**Comment by Disassembler0** [comment]
There are
- `DisableUpdateRestart` to disable automatic restart after update (not sure how well it works on latest builds though).
- `DisableUpdateMSRT` to stop offering *Malicious Software Removal Tool*.
- `DisableUpdateDriver` to stop offering driver updates.
- `SetP2PUpdateLocal` to restrict the peer-to-peer update distribution mechanism to local network.

There is no tweak to disable Windows Update completely and I strongly advise you against doing so.
