### ISSUE TITLE
this should be a gist

### ISSUE THREAD

**Issue by johnypony3** [Disassembler0/Win10-Initial-Setup-Script#6]
this would be very helpful in a packet/vagrant generated environment, having it in a repo makes it much more difficult than being able to pull a gist down.

**Comment by Disassembler0** [comment]
```
Invoke-WebRequest https://raw.githubusercontent.com/Disassembler0/Win10-Initial-Setup-Script/master/Win10.ps1
```
Does not seem that difficult to me.
