### ISSUE TITLE
Additional third party bloat

### ISSUE THREAD

**Issue by iamteerawut** [Disassembler0/Win10-Initial-Setup-Script#60]
I found new third party bloat after re-install Windows 10 that not included in the script

`Get-AppxPackage "DolbyLaboratories.DolbyAccess" | Remove-AppxPackage`

**Comment by alirobe** [comment]
My surface doesn't have this. This is frequently found on OEM installs of Windows, is yours an OEM build?

**Comment by iamteerawut** [comment]
No, I'm not using OEM, I custom build my PC. I'm downloading Windows 10 ISO from Microsoft.

**Comment by mhujer** [comment]
I had it in the clear install of W10 Pro 64bit (EN US) as well. I created the installer using the Media Creation Tool.

**Comment by Ianonn21** [comment]
I also have started getting this piece of bloatware on clean installs of W10 (Home, Pro). The bloatware installations do somewhat depend on your location and locale settings (I administer a few en-us installs with en-us and/or cs-cz/cs-cy locales and also one or two plain cs-cz installs and I have observed not all of them get the same bloatware), so not everyone gets the same 'package'.

I believe there is a group policy setting to disable these under "Computer Configuration --> Administrative Templates --> Windows Components --> Cloud Content" called "Turn off Microsoft consumer experiences" but I am afraid Microsoft no longer follows this setting as stricly as we would all like to.
