### ISSUE TITLE
Disable <insert> and <caps lock> key

### ISSUE THREAD

**Issue by jankatins** [Disassembler0/Win10-Initial-Setup-Script#70]
I find these two keys very annoying (both when I press them or when I get called by my parents...).

This contains an example how to disable it with some registry magic: https://www.wikihow.com/Disable-the-Capslock-Key-in-Windows (method 2 disables both).

The gist:

Add a new binary value under HKLM\System\CurrentControlSet\Control\Keyboard Layout ->  "Scancode Map"

Values: 

```
INSERT alone:    00000000 00000000 02000000 000052E0 00000000
CAPS LOCK alone: 00000000 00000000 02000000 00003A00 00000000
BOTH:            00000000 00000000 03000000 000052E0 00003A00 00000000
```

Explanation for the keymaps are here: https://www.howtogeek.com/howto/windows-vista/disable-caps-lock-key-in-windows-vista/

I can send a PR for the most trivial case: setting both at once via a DisableInsertAndCapsLockKey (and EnableInsertAndCapsLockKey which deletes the value again). IMO this should be two different methods (DisableCapsLockKey and DisableInsertKey) and it should take already replaced stuff into account, but my powershell is not good enough to parse that string and make the adjustments on the fly.

Would you take such a "simple" PR?

**Comment by Disassembler0** [comment]
Interesting topic. I must say that out of the several hundreds of PCs I have built, installed and supported over the span of last 10+ years, I could count such requirements on the fingers of one hand.

Although I can see what kind of problems do BFUs have with the Insert key, I personally find it very useful especially when copy-pasting stuff from terminals which have Ctrl key combinations reserved for other things (e.g. Ctrl+C for interrupt, so I have to use Ctrl+Insert for copying instead). As for the Caps Lock and Scroll Lock, more often then disabling them, I see remapping them to something useful, like [Ctrl](https://www.experts-exchange.com/articles/2155/Keyboard-Remapping-CAPSLOCK-to-Ctrl-and-Beyond.html) or [Esc](https://github.com/iliekturtles/Win10-Initial-Setup-Script/commit/ef0fcbbabcc5f3fe4b14ef201d2aa5df82b23a92).

I'm not really fond of such tweaks as they go against the expected functionality, but even if I'd agree to adding them and having them disabled by default, I see potential problems with their implementation. If they would be in separate tweaks, one for each key (which they should), you'd need to introduce some logic which checks the current state of the `Scancode Map` registry and adds or subtracts the appropriate scancode and increments or decrements the counter at the same time. The tweaks also shouldn't interfere with any other scancodes added by the user or the script itself to ensure that repeated runs will always result in correct values. I'm not saying that it's impossible, but I'm afraid that such logic may prove to be hard to implement in a clear, concise and easy-to-read way. Feel free to give it a shot, though... or don't and simply add the desired functionality using hardcoded values in your own fork.

**Comment by jankatins** [comment]
I'm fine with keeping this as a local script I have to run.

Thanks for making this script, this helps a lot, BTW!
