### ISSUE TITLE
Request: taskbar combining customization

### ISSUE THREAD

**Issue by sztanpet** [Disassembler0/Win10-Initial-Setup-Script#78]
I would humbly like to request the addition of this option :)

Right now I always want to disable combining taskbar buttons by

```Set-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "TaskbarGlomLevel" -Type DWord -Value 2```

the values are:

- to always combine, hide labels (default): 0
- combine when taskbar is full: 1
- never combine: 2

Thank you

**Comment by Disassembler0** [comment]
This would be another thing along with showing taskbar search (#55), control panel icon size (#45) and possibly other things which are beyond simple "do / undo" pair and require 3 or more states instead. I'll think about if I want such tweaks in the script and how to implement them to be understandable and not collide with future developments plans which I have for the script.
