### ISSUE TITLE
Request: Never combine taskbar buttons

### ISSUE THREAD

**Issue by Qrzysio** [Disassembler0/Win10-Initial-Setup-Script#93]
Could you add a new feature that sets "Combine taskbar buttons" option to "Never"?

It is in `Settings -> Personalisation -> Taskbar -> "Combine taskbar buttons" `. Thank you.

**Comment by Disassembler0** [comment]
`SetTaskbarCombineNever` is supposed to do that. Is there anything wrong with it?

https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/e3af426cb5e2bb6b2fa377d14254db32402e52bd/Win10.ps1#L1287-L1292

**Comment by Disassembler0** [comment]
Tested just now. `SetTaskbarCombineNever` works.
