### ISSUE TITLE
EnableMeltdownCompatFlag no longer needed

### ISSUE THREAD

**Issue by Zero3** [Disassembler0/Win10-Initial-Setup-Script#98]
According to https://support.microsoft.com/en-us/help/4072699/windows-security-updates-and-antivirus-software:

> Our recent work with our anti-virus (AV) partners on compatibility with Windows updates has now reached a sustained level of broad ecosystem compatibility.  Based on our analysis of available data, we are now lifting the AV compatibility check for the March 2018 Windows security updates for supported Windows 10 devices via Windows Update.  We continue to require that AV software is compatible and in cases where there are known issues of AV driver compatibility, we will block those devices from updates to avoid any issues. We recommend customers check with their AV provider on compatibility of their installed AV software product.

Maybe you want to keep the flag around anyway. I don't know. I just wanted to let you know about this update :).

**Comment by Disassembler0** [comment]
Yeah, ***security** updates for **supported** Windows 10 devices* sounds rather ambiguous. The tweak is commented by default anyway, so it doesn't hurt to keep it around for a little bit longer.

Thanks for the info.
